networks:
  proxy:
    external: true
  socket-proxy:
  default:

services:

  komodo-mongo:
    image: mongo:8
    container_name: komodo-mongo
    hostname: komodo-mongo
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - default
    volumes:
      - ${DOCKER_APP_DATA_DIR:?}/komodo/mongo/data/configdb:/data/configdb
      - ${DOCKER_APP_DATA_DIR:?}/komodo/mongo/data/db:/data/db
      - /etc/localtime:/etc/localtime:ro
    environment:
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:?}
      MONGO_INITDB_ROOT_USERNAME: komodo
    command: --quiet --wiredTigerCacheSizeGB 0.25
    labels:
      - komodo.skip

  komodo:
    image: ghcr.io/mbecker20/komodo:latest
    container_name: komodo
    hostname: komodo
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - default
    depends_on:
      - komodo-mongo
    volumes:
      - ${DOCKER_APP_DATA_DIR:?}/komodo/komodo/action-cache:/action-cache
      - ${DOCKER_APP_DATA_DIR:?}/komodo/komodo/repo-cache:/repo-cache
      - ${DOCKER_APP_DATA_DIR:?}/komodo/komodo/syncs:/syncs
      - /etc/localtime:/etc/localtime:ro
    environment:
      KOMODO_DATABASE_ADDRESS: komodo-mongo:27017
      KOMODO_DATABASE_PASSWORD: ${MONGO_PASSWORD:?}
      KOMODO_DATABASE_USERNAME: komodo
      KOMODO_DISABLE_CONFIRM_DIALOG: ${KOMODO_DISABLE_CONFIRM_DIALOG:-true}
      KOMODO_DISABLE_NON_ADMIN_CREATE: ${KOMODO_DISABLE_NON_ADMIN_CREATE:-false}
      KOMODO_DISABLE_USER_REGISTRATION: ${KOMODO_DISABLE_USER_REGISTRATION:-false}
      KOMODO_ENABLE_NEW_USERS: ${KOMODO_ENABLE_NEW_USERS:-false}
      KOMODO_FIRST_SERVER: ${KOMODO_FIRST_SERVER:-}
      KOMODO_HOST: https://komodo.${DOMAIN_NAME:?}
      KOMODO_JWT_SECRET: ${KOMODO_JWT_SECRET:?}
      KOMODO_KEEP_ALERTS_FOR_DAYS: ${KOMODO_KEEP_ALERTS_FOR_DAYS:-28}
      KOMODO_KEEP_STATS_FOR_DAYS: ${KOMODO_KEEP_STATS_FOR_DAYS:-28}
      KOMODO_LOCAL_AUTH: ${KOMODO_LOCAL_AUTH:-true}
      KOMODO_LOGGING_LEVEL: ${KOMODO_LOGGING_LEVEL:-info}
      KOMODO_MONITORING_INTERVAL: ${KOMODO_MONITORING_INTERVAL:-15-sec}
      KOMODO_PASSKEY: ${KOMODO_PASSKEY:?}
      KOMODO_RESOURCE_POLL_INTERVAL: ${KOMODO_RESOURCE_POLL_INTERVAL:-5-min}
      KOMODO_TITLE: Komodo - komodo.${DOMAIN_NAME:?}
      KOMODO_TRANSPARENT_MODE: ${KOMODO_TRANSPARENT_MODE:-false}
      KOMODO_UI_WRITE_DISABLED: ${KOMODO_UI_WRITE_DISABLED:-false}
    labels:
      - komodo.skip
      - traefik.http.routers.komodo-rtr.rule=Host(`komodo.${DOMAIN_NAME:?}`)
      - traefik.http.services.komodo-svc.loadBalancer.server.port=9120

  komodo-socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: komodo-socket-proxy
    hostname: komodo-socket-proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /run
    networks:
      - socket-proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_SOCKET:?}:/var/run/docker.sock
    environment:
      ALLOW_RESTARTS: 1
      ALLOW_START: 1
      ALLOW_STOP: 1
      CONTAINERS: 1
      EXEC: 1
      IMAGES: 1
      INFO: 1
      NETWORKS: 1
      POST: 1
      SERVICES: 1
    labels:
      - komodo.skip

  komodo-periphery:
    image: ghcr.io/mbecker20/periphery:latest
    container_name: komodo-periphery
    hostname: komodo-periphery
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - default
      - socket-proxy
    depends_on:
      - komodo-socket-proxy
    volumes:
      - ${DOCKER_COMPOSE_DIR:?}:/etc/komodo/stacks
      - /proc:/proc
      - /etc/localtime:/etc/localtime:ro
    environment:
      DOCKER_HOST: tcp://komodo-socket-proxy:2375
      PERIPHERY_PASSKEYS: ${KOMODO_PASSKEY:?}
    labels:
      - komodo.skip
