#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${DOCKER_DIR}/scripts/common.bash"

copy_env_file_template

prompt_set_env_file_password_val 'MONGO_PASSWORD'
prompt_set_env_file_password_val 'KOMODO_PASSKEY'
prompt_set_env_file_password_val 'KOMODO_JWT_SECRET'
