#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${DOCKER_DIR}/scripts/functions.bash"

env_file="$(env_file)"
readonly env_file
if ! file_exists "${env_file}"; then
  cp "${env_file}.template" "${env_file}"
fi
function set_var() {
  set_env_file_var_if_not_defined "${env_file}" "$1" "${2:-}"
}

set_var 'MONGO_PASSWORD' 'pwgen --secure --num-passwords 1 64'
set_var 'KOMODO_PASSKEY' 'pwgen --secure --num-passwords 1 64'
set_var 'KOMODO_JWT_SECRET' 'pwgen --secure --num-passwords 1 64'
