include:
  - ../traefik-proxy-network.yaml

services:
  changedetection:
    extends:
      file: ../service-defaults.yaml
      service: service-defaults
    image: ${CHANGEDETECTION_IMAGE:-dgtlmoon/changedetection.io}:${CHANGEDETECTION_IMAGE_TAG:-latest}
    container_name: changedetection
    hostname: changedetection
    volumes:
      - ${DOCKER_APP_DATA_DIR:?}/changedetection:/datastore
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.changedetection-rtr.entryPoints=websecure
      - traefik.http.routers.changedetection-rtr.rule=Host(`changedetection.${DOMAIN_NAME:?}`)
      - traefik.http.services.changedetection-svc.loadBalancer.server.port=5000
