networks:
  proxy:
    external: true

services:
  changedetection:
    image: ${CHANGEDETECTION_IMAGE:-dgtlmoon/changedetection.io}:${CHANGEDETECTION_IMAGE_TAG:-latest}
    container_name: changedetection
    hostname: changedetection
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - ${DOCKER_APP_DATA_DIR:?}/changedetection:/datastore
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.docker.network=proxy
      - traefik.enable=true
      - traefik.http.routers.changedetection-rtr.entryPoints=websecure
      - traefik.http.routers.changedetection-rtr.middlewares=default-chain-mdw@file
      - traefik.http.routers.changedetection-rtr.rule=Host(`changedetection.${DOMAIN_NAME:?}`)
      - traefik.http.services.changedetection-svc.loadBalancer.server.port=5000
