http:
  middlewares:

    crowdsec-bouncer-mdw:
      forwardauth:
        address: http://crowdsec-bouncer:8080/api/v1/forwardAuth
        trustForwardHeader: true

    geolocation-filter-mdw:
      forwardauth:
        address: http://traefik-geoip-filter:8080/traefik

    ip-allow-list-mdw:
      ipAllowList:
        sourceRange:
          - 127.0.0.1/32
          - 100.64.0.0/10

    rate-limit-mdw:
      rateLimit:
        average: 100
        burst: 50

    secure-headers-mdw:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlMaxAge: 100
        browserXssFilter: true
        contentSecurityPolicy: "default-src 'self' 'unsafe-inline' 'unsafe-eval'"
        contentTypeNosniff: true
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https
        customResponseHeaders:
          server: ""
          X-Forwarded-Proto: https
          X-Powered-By: ""
          X-Robots-Tag: noarchive,noimageindex,none,nosnippet,notranslate
        forceSTSHeader: true
        frameDeny: false
        hostsProxyHeaders:
          - X-Forwarded-Host
        permissionsPolicy: camera=(), geolocation=(), microphone=(), payment=(), usb=(), vr=()
        referrerPolicy: same-origin
        sslProxyHeaders:
          X-Forwarded-Proto: https
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 63072000

    auth-mdw:
      forwardauth:
        address: http://authelia:9091/api/verify?rd=https://authelia.{{ env "DOMAIN_NAME" }}/
        authResponseHeaders:
          - Remote-Email
          - Remote-Groups
          - Remote-Name
          - Remote-User
        trustForwardHeader: true

    compress-mdw:
      compress: {}

    default-chain-mdw:
      chain:
        middlewares:
          - crowdsec-bouncer-mdw@file
          - geolocation-filter-mdw@file
          - ip-allow-list-mdw@file
          - rate-limit-mdw@file
          - secure-headers-mdw@file
          - compress-mdw@file
          - auth-mdw@file
