networks:
  proxy:
    external: true

services:
  whoami:
    image: ${WHOAMI_IMAGE:-traefik/whoami}:${WHOAMI_IMAGE_TAG:-latest}
    container_name: whoami
    hostname: whoami
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      WHOAMI_NAME: whoami.${DOMAIN_NAME:?}
    labels:
      - traefik.docker.network=proxy
      - traefik.enable=true
      - traefik.http.routers.whoami-rtr.entryPoints=websecure
      - traefik.http.routers.whoami-rtr.middlewares=default-chain-mdw
      - traefik.http.routers.whoami-rtr.rule=Host(`whoami.${DOMAIN_NAME:?}`)
      - traefik.http.services.whoami-svc.loadBalancer.server.port=80
