include:
  - ../defaults.yaml

services:
  openspeedtest:
    <<: *container-defaults
    image: ${OPENSPEEDTEST_IMAGE:-openspeedtest/latest}:${OPENSPEEDTEST_IMAGE_TAG:-latest}
    container_name: openspeedtest
    hostname: openspeedtest
    volumes:
      - *localtime-bind
    environment:
      SET_SERVER_NAME: openspeedtest.${DOMAIN_NAME:?}
    labels:
      - traefik.enable=true
      - traefik.http.routers.openspeedtest.entryPoints=websecure
      - traefik.http.routers.openspeedtest.rule=Host(`openspeedtest.${DOMAIN_NAME:?}`)
