networks:
  proxy:
    external: true
  socket-proxy:

services:

  portainer-socket-proxy:
    image: ${SOCKET_PROXY_IMAGE:-lscr.io/linuxserver/socket-proxy}:${SOCKET_PROXY_IMAGE_TAG:-latest}
    container_name: portainer-socket-proxy
    hostname: portainer-socket-proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /run
    networks:
      - socket-proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_SOCKET:?}:/var/run/docker.sock
    environment:
      ALLOW_START: 1
      ALLOW_STOP: 1
      ALLOW_RESTARTS: 1
      CONTAINERS: 1
      EXEC: 1
      IMAGES: 1
      INFO: 1
      NETWORKS: 1
      VOLUMES: 1

  portainer:
    image: ${PORTAINER_IMAGE:-portainer/portainer-ce}:${PORTAINER_IMAGE_TAG:-latest}
    container_name: portainer
    hostname: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - socket-proxy
    depends_on:
      - portainer-socket-proxy
    user: ${PUID:?}:${PGID:?}
    volumes:
      - ${DOCKER_APP_DATA_DIR:?}/portainer/data:/data
      - /etc/localtime:/etc/localtime:ro
    command: --host tcp://portainer-socket-proxy:2375
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer-rtr.rule=Host(`portainer.${DOMAIN_NAME:?}`)
      - traefik.http.services.portainer-svc.loadBalancer.server.port=9000
