#!/usr/bin/env bash

set -eo pipefail

for env_var in \
  DOMAIN_NAME \
  PUID \
  PGID \
  DOCKER_TZ \
  DOCKER_COMPOSE_DIR \
  DOCKER_APP_DATA_DIR \
  DOCKER_SOCKET \
  DATA_DIR \
  RESTIC_BACKUP_DIR; do
    if [[ -z "${env_var}" ]]; then
      die='DIE'
      echo "${env_var} is not set to a non-empty value"
    fi
done

if [[ -z "${die}" ]]; then
  echo 'Fix the missing env vars and re-run this script'
  exit 1
fi

set -u

mkdir --parents "${DOCKER_APP_DATA_DIR}"

# restic
sudo mkdir --parents "${RESTIC_BACKUP_DIR}"
sudo chown --recursive "${USER}:" "${RESTIC_BACKUP_DIR}"

# filebrowser
mkdir --parents "${DOCKER_APP_DATA_DIR}/filebrowser"
touch "${DOCKER_APP_DATA_DIR}/filebrowser/filebrowser.db"
