#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${DOCKER_COMPOSE_DIR}/functions.bash"

## TODO run restic backups
## TODO run security scans
## TODO run clamav

(
  if container_is_running 'crowdsec'; then
    docker exec 'crowdsec' cscli hub update
    docker exec 'crowdsec' cscli hub upgrade
  fi
) 2>&1 >> "${DOCKER_COMPOSE_DIR}/daily-tasks.log"
