#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${DOCKER_DIR}/functions.bash"

for env_var in \
  BACKUP_DIR \
  DATA_DIR \
  DOCKER_APP_DATA_DIR \
  DOCKER_COMPOSE_DIR \
  DOCKER_DIR \
  DOCKER_LOGS_DIR \
  DOCKER_SOCKET \
  DOCKER_TZ \
  DOMAIN_NAME \
  DOMAIN_NAME_REGEX \
  PGID \
  PUID \
  TAILNET_IP \
  USER; do
    if [[ -z "${env_var:-}" ]]; then
      die='DIE'
      log "${env_var} is not set to a non-empty value"
    fi
done

if [[ -n "${die:-}" ]]; then
  die 'Fix the missing env vars and re-run this script'
fi

create_dir "${DOCKER_APP_DATA_DIR}"
create_dir "${DOCKER_LOGS_DIR}"

proxy_network='proxy'
if ! docker network inspect "${proxy_network}" &> '/dev/null'; then
  log "Creating ${proxy_network} network"
  docker network create "${proxy_network}" --subnet "${DOCKER_PROXY_NETWORK_SUBNET_CIDR}" --gateway "${DOCKER_PROXY_NETWORK_GATEWAY}"
  log "Created ${proxy_network} network"
fi

log 'Enabling daily-tasks service'
readonly systemd_service_dir="${XDG_CONFIG_HOME}/systemd/user"
copy_file "${DOCKER_DIR}/systemd/daily-tasks.service" "${systemd_service_dir}/daily-tasks.service"
copy_file "${DOCKER_DIR}/systemd/daily-tasks.timer" "${systemd_service_dir}/daily-tasks.timer"
systemctl --user --quiet daemon-reload
enable_user_service_unit 'daily-tasks.timer'
log 'Enabled daily-tasks service'

if promp_ny "Run init scripts?"; then
  init_scripts="$(find "${DOCKER_COMPOSE_DIR}" -mindepth 2 -type f -name 'init' | sort)"
  for init_script in ${init_scripts}; do
    init_script_dir="$(dirname "${init_script}")"
    stack_name="$(basename "${init_script_dir}")"
    if prompt_ny "Run ${stack_name}/init?"; then
      log "Running ${stack_name}/init"
      "${init_script}"
      log "Ran ${stack_name}/init"
    fi
  done
fi

git update-index --assume-unchanged "${DOCKER_DIR}/managed-stacks"

if [[ ! -s "${DOCKER_DIR}/managed-stacks" ]]; then
  log "Remember to add stack names to managed-stacks"
fi
