#!/usr/bin/env bash

set -euo pipefail

for env_var in \
  DOMAIN_NAME \
  PUID \
  PGID \
  DOCKER_TZ \
  DOCKER_COMPOSE_DIR \
  DOCKER_APP_DATA_DIR \
  DOCKER_SOCKET \
  DATA_DIR \
  RESTIC_BACKUP_DIR; do
    if [[ -z "${env_var:-}" ]]; then
      die='DIE'
      echo "${env_var} is not set to a non-empty value"
    fi
done

if [[ -n "${die:-}" ]]; then
  echo 'Fix the missing env vars and re-run this script'
  exit 1
fi

readonly proxy_network='proxy'
if ! docker network inspect "${proxy_network}" &> '/dev/null'; then
  docker network create "${proxy_network}"
fi

mkdir --parents "${DOCKER_APP_DATA_DIR}"

env_templates="$(find . -mindepth 2 -type f -name '.env.template')"
for env_template in ${env_templates}; do
  env_file="${env_template%%.template}"
  if [[ ! -f "${env_file}" ]]; then
    echo "Creating ${env_file:2}"
    cp "${env_template}" "${env_file}"
  fi
done

function prompt_yn() {
  REPLY=''
  while [[ "${REPLY}" != 'y' && "${REPLY}" != 'n' ]]; do
    echo -e -n "\033[0;33m$1 [y/N]: \033[0m"
    read -r
    if [[ "${REPLY}" == [yY] ]]; then
      REPLY='y'
    elif [[ "${REPLY}" == '' || "${REPLY}" == [nN] ]]; then
      REPLY='n'
    fi
  done
  [[ "${REPLY}" == 'y' ]]
}

init_scripts="$(find . -mindepth 2 -type f -name 'init')"
for init_script in ${init_scripts}; do
  if prompt_yn "Run ${init_script:2}?"; then
    echo "Running ${init_script:2}"
    "${init_script}"
  fi
done
