#!/usr/bin/env bash

set -euo pipefail

for env_var in \
  DOMAIN_NAME \
  PUID \
  PGID \
  DOCKER_TZ \
  DOCKER_COMPOSE_DIR \
  DOCKER_APP_DATA_DIR \
  DOCKER_SOCKET \
  DATA_DIR \
  RESTIC_BACKUP_DIR; do
    if [[ -z "${env_var:-}" ]]; then
      die='DIE'
      echo "${env_var} is not set to a non-empty value"
    fi
done

if [[ -n "${die:-}" ]]; then
  echo 'Fix the missing env vars and re-run this script'
  exit 1
fi

readonly traefik_network='traefik-proxy'
if ! docker network inspect "${traefik_network}" &> '/dev/null'; then
  docker network create "${traefik_network}"
fi

mkdir --parents "${DOCKER_APP_DATA_DIR}"

# restic
mkdir --parents "${RESTIC_BACKUP_DIR}"

# filebrowser
readonly filebrowser_data_dir="${DOCKER_APP_DATA_DIR}/filebrowser"
mkdir --parents "${filebrowser_data_dir}"
touch "${filebrowser_data_dir}/filebrowser.db"

# guacamole postgres
readonly guacamole_postgres_init_dir="${DOCKER_APP_DATA_DIR}/guacamole-postgres/init"
readonly guacamole_postgres_init_file="${guacamole_postgres_init_dir}/init-db.sql"
mkdir --parents "${guacamole_postgres_init_dir}"
if [[ ! -f "${guacamole_postgres_init_file}" ]]; then
  docker run --rm guacamole/guacamole:latest /opt/guacamole/bin/initdb.sh --postgresql > "${guacamole_postgres_init_file}"
fi
