#!/usr/bin/env bash

set -euo pipefail

while read -r stack; do
  if [[ -z "${stack}" ]]; then
    continue
  fi
  docker compose --file "${DOCKER_COMPOSE_DIR}/${stack}/compose.yaml" pull
done < "${DOCKER_DIR}/managed-stacks"
