#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${DOCKER_COMPOSE_DIR}/functions.bash"

while read -r stack; do
  docker compose --file "${stack}/compose.yaml" up --detach
done < "$(this_script_dir)/stacks-to-start"
