#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${DOCKER_DIR}/functions.bash"

while read -r stack; do
  docker compose --file "${DOCKER_COMPOSE_DIR}/${stack}/compose.yaml" up --detach
done < "${DOCKER_DIR}/managed-stacks"
