#!/usr/bin/env bash

set -euo pipefail

while read -r compose_file; do
  docker compose --file "${compose_file}" down --remove-orphans
done < <(docker compose ls | tail --lines '+2' | awk '{ print $3 }' | sort)
