#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${DOCKER_DIR}/scripts/common.bash"

while read -r stack; do
  if [[ -z "${stack}" ]]; then
    continue
  fi
  if file_exists "${DOCKER_COMPOSE_DIR}/${stack}/run"; then
    log "Skipping: ${stack}"
  else
    docker compose --file "${DOCKER_COMPOSE_DIR}/${stack}/compose.yaml" down --remove-orphans
  fi
done < "${DOCKER_DIR}/managed-stacks"
