networks:
  proxy:
    external: true

services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - ${DOCKER_APP_DATA_DIR:?}/freshrss/var/www/FreshRSS/data:/var/www/FreshRSS/data
      - ${DOCKER_APP_DATA_DIR:?}/freshrss/var/www/FreshRSS/extensions:/var/www/FreshRSS/extensions
      - /etc/localtime:/etc/localtime:ro
    environment:
      CRON_MIN: ${CRON_MIN:-13,43}
      TRUSTED_PROXY: ${DOCKER_NETWORK_CIDR:?}
      FRESHRSS_INSTALL: --auth-type http_auth --base-url https://freshrss.${DOMAIN_NAME:?} --default-user ${USER:?}
    labels:
      - deunhealth.restart.on.unhealthy=true
      - traefik.enable=true
      - traefik.http.routers.freshrss-rtr.rule=Host(`freshrss.${DOMAIN_NAME:?}`)
      - traefik.http.services.freshrss-svc.loadBalancer.server.port=80
