#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${DOCKER_COMPOSE_DIR}/functions.bash"

readonly app_data_dir="${DOCKER_APP_DATA_DIR}/komodo"
create_dir_or_change_ownership "${app_data_dir}" \
  "${app_data_dir}/komodo/repo-cache" \
  "${app_data_dir}/komodo/syncs" \
  "${app_data_dir}/komodo/action-cache" \
  "${app_data_dir}/mongo/data" \
  "${app_data_dir}/mongo/config"

readonly env_file="$(env_file)"
set_env_file_var_if_not_defined "${env_file}" 'MONGO_PASSWORD'
set_env_file_var_if_not_defined "${env_file}" 'KOMODO_PASSKEY'
set_env_file_var_if_not_defined "${env_file}" 'KOMODO_JWT_SECRET'
