http:
  routers:
    cockpit-rtr:
      entryPoints:
        - websecure
      rule: 'Host(`cockpit.{{ env "DOMAIN_NAME" }}`)'
      service: cockpit
  services:
    cockpit-svc:
      loadBalancer:
        servers:
          - url: 'https://{{ env "DOMAIN_NAME" }}:9090'
        serversTransport: cockpit
  serversTransports:
    cockpit-stx:
      insecureSkipVerify: true
