http:
  middlewares:
    secure-headers-mdw:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - X-Forwarded-Host
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        # forceSTSHeader: true # TODO This is a good thing, but it can be tricky. Enable after everything works.
        customFrameOptionsValue: SAMEORIGIN
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: same-origin
        permissionsPolicy: camera=(), microphone=(), geolocation=(), payment=(), usb=(), vr=()
        customResponseHeaders:
          X-Robots-Tag: none,noarchive,nosnippet,notranslate,noimageindex
          server: ""
