http:
  ## TODO route hello to hello-world
  routers:
    hello-world:
      entryPoints:
        - websecure
      rule: 'Host(`hello-world.{{ env "DOMAIN_NAME" }}`)'
      service: hello-world
  services:
    hello-world:
      loadBalancer:
        servers:
          - url: 'http://{{ env "DOMAIN_NAME" }}:{{ env "HELLO_WORLD_PORT" }}'
