http:
  routers:
    webmin-rtr:
      entryPoints:
        - websecure
      middlewares:
        - default-chain-mdw
      rule: 'Host(`webmin.{{ env "DOMAIN_NAME" }}`)'
      service: webmin-svc
  services:
    webmin-svc:
      loadBalancer:
        servers:
          - url: 'https://{{ env "DOMAIN_NAME" }}:10000'
        serversTransport: webmin-stx
  serversTransports:
    webmin-stx:
      insecureSkipVerify: true
