http:
  routers:
    webmin-rtr:
      entryPoints:
        - websecure
      rule: 'Host(`webmin.{{ env "DOMAIN_NAME" }}`)'
      service: webmin
  services:
    webmin-svc:
      loadBalancer:
        servers:
          - url: 'https://{{ env "DOMAIN_NAME" }}:10000'
        serversTransport: webmin
  serversTransports:
    webmin-stx:
      insecureSkipVerify: true
