http:
  routers:
    webmin:
      entryPoints:
        - websecure
      rule: 'Host(`webmin.{{ env "DOMAIN_NAME" }}`)'
      service: webmin
  services:
    webmin:
      loadBalancer:
        servers:
          - url: 'https://{{ env "DOMAIN_NAME" }}:10000'
        serversTransport: webmin
  serversTransports:
    webmin:
      insecureSkipVerify: true
