include:
  - ../traefik-proxy-network.yaml

services:
  privatebin:
    extends:
      file: ../service-defaults.yaml
      service: service-defaults
    image: ${PRIVATEBIN_IMAGE:-privatebin/fs}:${PRIVATEBIN_IMAGE_TAG:-latest}
    container_name: privatebin
    hostname: privatebin
    volumes:
      - ${DOCKER_APP_DATA_DIR:?}/privatebin/conf.php:/srv/cfg/conf.php:ro
      - ${DOCKER_APP_DATA_DIR:?}/privatebin/data:/srv/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: ${TZ:?}
    labels:
      - traefik.enable=true
      - traefik.http.routers.privatebin.entryPoints=websecure
      - traefik.http.routers.privatebin.rule=Host(`privatebin.${DOMAIN_NAME:?}`)
