networks:
  proxy:
    external: true

volumes:
  data:

services:
  privatebin:
    image: ${PRIVATEBIN_IMAGE:-privatebin/fs}:${PRIVATEBIN_IMAGE_TAG:-latest}
    container_name: privatebin
    hostname: privatebin
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - ./conf.php:/srv/cfg/conf.php:ro
      - data:/srv/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.privatebin-rtr.entryPoints=websecure
      - traefik.http.routers.privatebin-rtr.middlewares=default-chain-mdw@file
      - traefik.http.routers.privatebin-rtr.rule=Host(`privatebin.${DOMAIN_NAME:?}`)
      - traefik.http.services.privatebin-svc.loadBalancer.server.port=8080
