networks:
  proxy:
    external: true

services:
  privatebin:
    image: ${PRIVATEBIN_IMAGE:-privatebin/fs}:${PRIVATEBIN_IMAGE_TAG:-latest}
    container_name: privatebin
    hostname: privatebin
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    user: ${PUID:?}:${PGID:?}
    volumes:
      - ./conf.php:/srv/cfg/conf.php:ro
      - ${DOCKER_APP_DATA_DIR:?}/privatebin/srv/data:/srv/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.privatebin-rtr.rule=Host(`privatebin.${DOMAIN_NAME:?}`)
      - traefik.http.services.privatebin-svc.loadBalancer.server.port=8080
