## https://www.authelia.com/configuration/prologue/introduction/

access_control:
  # bypass, one_factor, two_factor, or deny
  default_policy: two_factor
  networks:
  - name: tailnet
    networks: 100.64.0.0/10
  rules:
    
authentication_backend:
  file:
    path: /users.yaml
    watch: true
  password_reset:
    disable: true

# totp, webauthn, or mobile_push
default_2fa_method: totp

## TODO test this
duo_api:
  hostname: {{ env "DUO_API_HOSTNAME" }}
  integration_key: {{ env "DUO_INTEGRATION_KEY" }}
  secret_key: {{ env "DUO_SECRET_KEY" }}
  enable_self_enrollment: true

log:
  file_path: /var/log/authelia.log
  # json, text.
  format: text
  keep_stdout: true
  # info, debug, trace
  level: {{ env "LOG_LEVEL" }}

## TODO email notifications
notifier:
  filesystem:
    filename: /notifications.txt

regulation:
  ban_time: 12h
  find_time: 10m
  max_retries: 5

session:
  cookies:
    - authelia_url: https://authelia.{{ env "DOMAIN_NAME" }}
      expiration: 1h
      domain: {{ env "DOMAIN_NAME" }}
      inactivity: 5m
      name: {{ env "DOMAIN_NAME" }}-authelia-session
      remember_me: 1d

storage:
  encryption_key: {{ env "STORAGE_ENCRYPTION_KEY" }}
  local:
    path: /config/db.sqlite3

theme: dark

totp:
  issuer: {{ env "DOMAIN_NAME" }}

webauthn:
  disable: true
