## https://www.authelia.com/configuration/prologue/introduction/

access_control:
  # bypass, one_factor, two_factor, or deny
  default_policy: two_factor
  networks:
  - name: local
    networks:
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
  - name: tailnet
    networks: 100.64.0.0/10
  rules:
    
authentication_backend:
  file:
    path: /users.yaml
    watch: true
  password_reset:
    disable: true

# totp, webauthn, or mobile_push
default_2fa_method: totp

## TODO
##
## Duo Push API Configuration
##
## Parameters used to contact the Duo API. Those are generated when you protect an application of type
## "Partner Auth API" in the management panel.
# duo_api:
  # disable: false
  # hostname: 'api-123456789.example.com'
  # integration_key: 'ABCDEF'
  ## Secret can also be set using a secret: https://www.authelia.com/c/secrets
  # secret_key: '1234567890abcdefghifjkl'
  # enable_self_enrollment: false

log:
  ## TODO - for crowdsec?
  file_path: /config/authelia.log
  # json, text.
  format: text
  keep_stdout: true
  # info, debug, trace
  level: {{ env "LOG_LEVEL" }}

notifier:
  filesystem:
    filename: /notifications.txt

regulation:
  ban_time: 12h
  find_time: 10m
  max_retries: 5

session:
  cookies:
    - authelia_url: https://authelia.{{ env "DOMAIN_NAME" }}
      expiration: 1h
      ## TODO?
      # default_redirection_url: 'https://www.example.com'
      domain: {{ env "DOMAIN_NAME" }}
      inactivity: 5m
      name: {{ env "DOMAIN_NAME" }}-authelia-session
      remember_me: 1d

storage:
  ## docker run --rm authelia/authelia:latest authelia crypto rand --length 64 --charset alphanumeric
  encryption_key: {{ env "STORAGE_ENCRYPTION_KEY" }}
  local:
    path: /config/db.sqlite3

theme: dark

totp:
  disable: false
  issuer: {{ env "DOMAIN_NAME" }}

webauthn:
  disable: true
