## https://www.authelia.com/configuration/prologue/introduction/

access_control:
  # bypass, one_factor, two_factor, or deny
  default_policy: one_factor
  networks:
  - name: local
    networks:
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
  - name: tailnet
    networks: 100.64.0.0/10
  ## TODO?
  # rules:
    
authentication_backend:
  file:
    path: /users.yaml
    watch: true
  password_reset:
    disable: true

# totp, webauthn, or mobile_push
default_2fa_method: totp

## TODO
##
## Duo Push API Configuration
##
## Parameters used to contact the Duo API. Those are generated when you protect an application of type
## "Partner Auth API" in the management panel.
# duo_api:
  # disable: false
  # hostname: 'api-123456789.example.com'
  # integration_key: 'ABCDEF'
  ## Secret can also be set using a secret: https://www.authelia.com/c/secrets
  # secret_key: '1234567890abcdefghifjkl'
  # enable_self_enrollment: false

log:
  ## TODO - for crowdsec?
  file_path: /config/authelia.log
  # json, text.
  format: text
  keep_stdout: true
  # info, debug, trace.
  level: debug

notifier:
  filesystem:
    filename: /notifications.txt
    
## TODO check on this when binding /etc/localtime
##
## NTP Configuration
##
## This is used to validate the servers time is accurate enough to validate TOTP.
# ntp:
  ## The address of the NTP server to connect to in the address common syntax.
  ## Format: [<scheme>://]<hostname>[:<port>].
  ## Square brackets indicate optional portions of the format. Scheme must be 'udp', 'udp4', or 'udp6'.
  ## The default scheme is 'udp'. The default port is '123'.
  # address: 'udp://time.cloudflare.com:123'

  ## NTP version.
  # version: 4

  ## Maximum allowed time offset between the host and the NTP server in the duration common syntax.
  # max_desync: '3 seconds'

  ## Disables the NTP check on startup entirely. This means Authelia will not contact a remote service at all if you
  ## set this to true, and can operate in a truly offline mode.
  # disable_startup_check: false

  ## The default of false will prevent startup only if we can contact the NTP server and the time is out of sync with
  ## the NTP server more than the configured max_desync. If you set this to true, an error will be logged but startup
  ## will continue regardless of results.
  # disable_failure: false

regulation:
  ban_time: 12h
  find_time: 10m
  max_retries: 5

session:
  cookies:
    - authelia_url: https://authelia.{{ env "DOMAIN_NAME" }}
      expiration: 1h
      ## TODO?
      # default_redirection_url: 'https://www.example.com'
      domain: {{ env "DOMAIN_NAME" }}
      inactivity: 5m
      name: {{ env "DOMAIN_NAME" }}-authelia-session
      remember_me: 1d

storage:
  ## docker run --rm authelia/authelia:latest authelia crypto rand --length 64 --charset alphanumeric
  encryption_key: {{ env "STORAGE_ENCRYPTION_KEY" }}
  local:
    path: /config/db.sqlite3

theme: dark

## TODO
totp:
  disable: false
  issuer: {{ env "DOMAIN_NAME" }}
