networks:
  proxy:
    external: true

services:
  it-tools:
    image: ${IT_TOOLS_IMAGE:-corentinth/it-tools}:${IT_TOOLS_IMAGE_TAG:-latest}
    container_name: it-tools
    hostname: it-tools
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.http.routers.it-tools-rtr.rule=Host(`it-tools.${DOMAIN_NAME:?}`)
      - traefik.http.services.it-tools-svc.loadBalancer.server.port=80
