#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${DOCKER_DIR}/compose/init-scripts-common.bash"

function wazuh_password_hash() {
  local wazuh_version="$(env_file_val 'WAZUH_VERSION')"
  local password="$(env_file_val "$1")"
  docker run \
    --rm \
    --interactive \
    --tty \
    "wazuh/wazuh-indexer:${wazuh_version}" \
    bash \
    /usr/share/wazuh-indexer/plugins/opensearch-security/tools/hash.sh --password "${password}" \
    | tr --complement --delete '[:print:]\n' \
    | tail --lines '1'
}

copy_env_file_template

prompt_set_env_file_val 'WAZUH_VERSION' 'https://hub.docker.com/r/wazuh/wazuh-manager/tags'
prompt_set_env_file_password_val 'API_PASSWORD'
prompt_set_env_file_password_val 'DASHBOARD_PASSWORD'
prompt_set_env_file_password_val 'INDEXER_PASSWORD'

certs_dir="${DOCKER_APP_DATA_DIR}/wazuh/certs"
readonly certs_dir
if ! dir_exists "${certs_dir}"; then
  log 'Generating indexer certificates'
  certs_conf_file="$(mktemp --directory)/certs.yaml"
  readonly certs_conf_file
  write_file "${certs_conf_file}" "\
nodes:
  indexer:
    - name: wazuh-indexer
      ip: wazuh-indexer.internal
  server:
    - name: wazuh-manager
      ip: wazuh-manager.internal"
  docker run \
    --rm \
    --volume "${certs_dir}:/certificates/" \
    --volume "${certs_conf_file}:/config/certs.yml" \
    wazuh/wazuh-certs-generator:0.0.2
  log 'Generated indexer certificates'
fi

root_create_app_data_dir \
  'wazuh/indexer/usr/share/wazuh-indexer/opensearch-security' \
  'wazuh/indexer/var/lib/wazuh-indexer'
sudo chown -R '1000:1000' "${DOCKER_APP_DATA_DIR}/wazuh/indexer/usr/share/wazuh-indexer"
sudo chown -R '1000:1000' "${DOCKER_APP_DATA_DIR}/wazuh/indexer/var/lib/wazuh-indexer"

readonly indexer_users_file="${DOCKER_APP_DATA_DIR}/wazuh/indexer/usr/share/wazuh-indexer/opensearch-security/internal_users.yml"
log 'Generating indexer users file'
indexer_password_hash="$(wazuh_password_hash 'INDEXER_PASSWORD')"
readonly indexer_password_hash
dashboard_password_hash="$(wazuh_password_hash 'DASHBOARD_PASSWORD')"
readonly dashboard_password_hash
write_file "${indexer_users_file}" "\
_meta:
  type: internalusers
  config_version: 2
admin:
  hash: ${indexer_password_hash}
  reserved: true
  backend_roles:
  - admin
  description: admin user
kibanaserver:
  hash: ${dashboard_password_hash}
  reserved: true
  description: kibanaserver user"
log 'Generated indexer users file'

root_create_app_data_dir \
  'wazuh/dashboard/usr/share/wazuh-dashboard/data/wazuh/config' \
  'wazuh/dashboard/usr/share/wazuh-dashboard/plugins/wazuh/public/assets/custom'
sudo chown -R '1000:1000' "${DOCKER_APP_DATA_DIR}/wazuh/dashboard/usr/share/wazuh-dashboard"

readonly dashboard_config_file="${DOCKER_APP_DATA_DIR}/wazuh/dashboard/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml"
log 'Generating dashboard hosts file'
api_password="$(env_file_val 'API_PASSWORD')"
readonly api_password
write_file "${dashboard_config_file}" "\
hosts:
  - 1513629884013:
      url: https://wazuh-manager.internal
      port: 55000
      username: wazuh-wui
      password: ${api_password}
      run_as: false"
log 'Generated dashboard hosts file'
