#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${DOCKER_DIR}/scripts/functions.bash"

env_file="$(env_file)"
readonly env_file
if ! file_exists "${env_file}"; then
  cp "${env_file}.template" "${env_file}"
fi

function password_hash() {
  local wazuh_version="$(get_var 'WAZUH_VERSION')"
  local password="$(get_var "$1")"
  docker run \
    --rm \
    --interactive \
    --tty \
    "wazuh/wazuh-indexer:${wazuh_version}" \
    bash \
    /usr/share/wazuh-indexer/plugins/opensearch-security/tools/hash.sh --password "${password}" \
    | tr --complement --delete '[:print:]\n' \
    | tail --lines '1'
}

set_var 'WAZUH_VERSION' 'https://hub.docker.com/r/wazuh/wazuh-manager/tags'
set_var 'API_PASSWORD' 'pwgen --symbols --num-passwords 1 64'
set_var 'DASHBOARD_PASSWORD' 'pwgen --num-passwords 1 64'
set_var 'INDEXER_PASSWORD' 'pwgen --num-passwords 1 64'

indexer_data_dir="${DOCKER_APP_DATA_DIR}/wazuh/indexer/var/lib/wazuh-indexer"
readonly indexer_data_dir
if ! dir_exists "${indexer_data_dir}"; then
  log "Creating indexer data dir"
  root_create_dir "${indexer_data_dir}"
  # indexer won't work if the data dir is not owned by 1000:1000
  sudo chown '1000:1000' "${indexer_data_dir}"
  log "Created indexer data dir"
fi

certs_dir="${DOCKER_APP_DATA_DIR}/wazuh/certs"
readonly certs_dir
if ! dir_exists "${certs_dir}"; then
  log "Generating indexer certificates"
  certs_conf_file="$(mktemp --directory)/certs.yaml"
  readonly certs_conf_file
  write_file "${certs_conf_file}" "\
nodes:
  indexer:
    - name: wazuh.indexer
      ip: wazuh.indexer
  server:
    - name: wazuh.manager
      ip: wazuh.manager
  dashboard:
    - name: wazuh.dashboard
      ip: wazuh.dashboard
"
  docker run \
    --rm \
    --volume "${certs_dir}:/certificates/" \
    --volume "${certs_conf_file}:/config/certs.yml" \
    wazuh/wazuh-certs-generator:0.0.2
  log "Generated indexer certificates"
fi

readonly indexer_users_file="${DOCKER_APP_DATA_DIR}/wazuh/indexer/usr/share/wazuh-indexer/opensearch-security/internal_users.yml"
log "Generating indexer users file"
indexer_password_hash="$(password_hash 'INDEXER_PASSWORD')"
readonly indexer_password_hash
dashboard_password_hash="$(password_hash 'DASHBOARD_PASSWORD')"
readonly dashboard_password_hash
root_write_file "${indexer_users_file}" "\
_meta:
  type: internalusers
  config_version: 2
admin:
  hash: ${indexer_password_hash}
  reserved: true
  backend_roles:
  - admin
  description: admin user
kibanaserver:
  hash: ${dashboard_password_hash}
  reserved: true
  description: kibanaserver user
"
log "Generated indexer users file"

readonly dashboard_hosts_file="${DOCKER_APP_DATA_DIR}/wazuh/dashboard/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml"
log "Generating dashboard hosts file"
api_password="$(get_var 'API_PASSWORD')"
readonly api_password
root_write_file "${dashboard_hosts_file}" "\
hosts:
  - ${HOSTNAME}:
      url: https://wazuh.manager
      port: 55000
      username: wazuh-wui
      password: ${api_password}
      run_as: false
"
log "Generated dashboard hosts file"
