networks:
  proxy:
    external: true

volumes:
  database:

services:
  filebrowser:
    image: ${FILEBROWSER_IMAGE:-filebrowser/filebrowser}:${FILEBROWSER_IMAGE_TAG:-latest}
    container_name: filebrowser
    hostname: filebrowser
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - ~:/srv
      - ./config.json:/.filebrowser.json
      - database:/database/
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.filebrowser-rtr.entryPoints=websecure
      - traefik.http.routers.filebrowser-rtr.middlewares=default-chain-no-auth-mdw@file
      - traefik.http.routers.filebrowser-rtr.rule=Host(`filebrowser.${DOMAIN_NAME:?}`)
      - traefik.http.routers.filebrowser-rtr.tls=true
      - traefik.http.services.filebrowser-svc.loadBalancer.server.port=80
