include:
  - ../proxy-network.yaml

services:
  filebrowser:
    image: ${FILEBROWSER_IMAGE:-filebrowser/filebrowser}:${FILEBROWSER_IMAGE_TAG:-latest}
    container_name: filebrowser
    hostname: filebrowser
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - ~:/srv
      - ./config.json:/.filebrowser.json
      - ${DOCKER_APP_DATA_DIR:?}/filebrowser/filebrowser.db:/database.db
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.filebrowser-rtr.entryPoints=websecure
      - traefik.http.routers.filebrowser-rtr.rule=Host(`filebrowser.${DOMAIN_NAME:?}`)
      - traefik.http.services.filebrowser-svc.loadBalancer.server.port=80
