#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${DOCKER_COMPOSE_DIR}/functions.bash"

readonly app_data_dir="${DOCKER_APP_DATA_DIR}/filebrowser"
create_dir_or_change_ownership "${app_data_dir}"

readonly filebrowser_db="${app_data_dir}/filebrowser.db"
create_or_overwrite_file "${filebrowser_db}" ''
