#!/usr/bin/env bash

set -euo pipefail

readonly filebrowser_data_dir="${DOCKER_APP_DATA_DIR}/filebrowser"
if [[ ! -d "${filebrowser_data_dir}" ]]; then
  echo "Creating ${filebrowser_data_dir}"
  mkdir --parents "${filebrowser_data_dir}"
  echo "Created ${filebrowser_data_dir}"
fi

readonly filebrowser_db="${filebrowser_data_dir}/filebrowser.db"
if [[ ! -f "${filebrowser_db}" ]]; then
  echo "Creating ${filebrowser_db}"
  touch "${filebrowser_db}"
  echo "Created ${filebrowser_db}"
fi
