#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${DOCKER_DIR}/scripts/functions.bash"

env_file="$(env_file)"
readonly env_file
if ! file_exists "${env_file}"; then
  cp "${env_file}.template" "${env_file}"
fi

set_var 'TUDUDI_SESSION_SECRET' 'pwgen --secure --num-passwords 1 64'
set_var 'TUDUDI_USER_EMAIL'
set_var 'TUDUDI_USER_PASSWORD'
