services:
  restart-notifier:
    image: index.docker.io/deduard/tools:restart-notifier-latest
    container_name: restart-notifier
    hostname: restart-notifier
    restart: unless-stopped
    network_mode: none
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_SOCKET:?}:/var/run/docker.sock
    environment:
      CRON_SCHEDULE: 0 5 * * *
      RESTART_CONTAINERS:
