networks:
  proxy:
    external: true

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    hostname: uptime-kuma
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - ${DOCKER_APP_DATA_DIR:?}/uptime-kuma/app/data:/app/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.uptime-redirect-mdw.redirectRegex.regex=^https://uptime\.${DOMAIN_NAME_REGEX:?}/(.*)
      - traefik.http.middlewares.uptime-redirect-mdw.redirectRegex.replacement=https://uptime-kuma.${DOMAIN_NAME:?}/$${1}
      - traefik.http.routers.uptime-kuma-rtr.rule=Host(`uptime-kuma.${DOMAIN_NAME:?}`)
      - traefik.http.routers.uptime-redirect-rtr.middlewares=uptime-redirect-mdw
      - traefik.http.routers.uptime-redirect-rtr.rule=Host(`uptime.${DOMAIN_NAME:?}`
      - traefik.http.services.uptime-kuma-svc.loadBalancer.server.port=3001
