#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${DOCKER_DIR}/compose/init-scripts-common.bash"

copy_env_file_template

prompt_set_env_file_password_val 'RESTIC_PASSWORD' 'Restic encryption key'
prompt_set_env_file_val 'B2_KEY_ID' 'Backblaze B2 application key ID'
prompt_set_env_file_val 'B2_KEY' 'Backblaze B2 application key'
prompt_set_env_file_val 'B2_BUCKET_ENDPOINT' 'Backblaze B2 endpoint - domain only'
prompt_set_env_file_val 'R2_KEY_ID' 'Cloudflare R2 application key ID'
prompt_set_env_file_val 'R2_KEY' 'Cloudflare R2 application key'
prompt_set_env_file_val 'R2_BUCKET_ENDPOINT' 'Cloudflare R2 endpoint - domain only'

create_dir "${BACKUP_DIR}/restic"

# $1 = repo desc
# $2 = service
function init_repo_if_not_exists() {
  local compose_file
  compose_file="$(this_script_dir)/compose.yaml"
  log "Checking if $1 repository exists"
  set +e
  docker compose --file "${compose_file}" run --rm "restic-$2" cat config > '/dev/null' 2>&1
  local exit_code="$?"
  set -e
  if [[ "${exit_code}" == '10' ]]; then
    log "$1 repository does not exist"
    if prompt_yn "Initialize $1 repository?"; then
      log "Initializing $1 repository"
      docker compose --file "${compose_file}" run --rm "restic-$2" init
      log "Initialized $1 repository"
    fi
  elif [[ "${exit_code}" != '0' ]]; then
    # run command again to print failure info
    docker compose --file "${compose_file}" run --rm "restic-$2" cat config
  else
    log "$1 repository exists"
  fi
}

init_repo_if_not_exists 'local' 'local'
init_repo_if_not_exists 'Backblaze B2' 'b2'
init_repo_if_not_exists 'Cloudflare R2' 'r2'
