#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${DOCKER_DIR}/scripts/functions.bash"

env_file="$(env_file)"
readonly env_file
if ! file_exists "${env_file}"; then
  cp "${env_file}.template" "${env_file}"
fi

set_var 'RESTIC_PASSWORD' 'Restic encryption key (pwgen --secure --num-passwords 1 64)'
set_var 'B2_KEY_ID' 'Backblaze B2 application key ID'
set_var 'B2_KEY' 'Backblaze B2 application key'
set_var 'B2_BUCKET_ENDPOINT' 'Backblaze B2 endpoint (domain only)'
set_var 'R2_KEY_ID' 'Cloudflare R2 application key ID'
set_var 'R2_KEY' 'Cloudflare R2 application key'
set_var 'R2_BUCKET_ENDPOINT' 'Cloudflare R2 endpoint (domain only)'

create_dir "${BACKUP_DIR}/restic"

# $1 = repo desc
# $2 = service
function init_repo_if_not_exists() {
  local compose_file
  compose_file="$(this_script_dir)/compose.yaml"
  log "Checking if $1 repository exists"
  set +e
  docker compose --file "${compose_file}" run --rm "restic-$2" cat config > '/dev/null' 2>&1
  local exit_code="$?"
  set -e
  if [[ "${exit_code}" == '10' ]]; then
    log "$1 repository does not exist"
    if prompt_yn "Initialize $1 repository?"; then
      log "Initializing $1 repository"
      docker compose --file "${compose_file}" run --rm "restic-$2" init
      log "Initialized $1 repository"
    fi
  elif [[ "${exit_code}" != '0' ]]; then
    # run command again to print failure info
    docker compose --file "${compose_file}" run --rm "restic-$2" cat config
  else
    log "$1 repository exists"
  fi
}

init_repo_if_not_exists 'local' 'local'
init_repo_if_not_exists 'Backblaze B2' 'b2'
init_repo_if_not_exists 'Cloudflare R2' 'r2'
