include:
  - ../traefik-proxy-network.yaml

x-guacamole-mysql-environment: &guacamole-mysql-environment
  MYSQL_DATABASE: guacamole_db
  MYSQL_PASSWORD: ${MYSQL_PASSWORD:?}
  MYSQL_USER: guacamole_user

services:

  guacamole-mysql:
    extends:
      file: ../service-defaults.yaml
      service: service-defaults
    image: ${MYSQL_IMAGE:-mysql}:${MYSQL_IMAGE_TAG:-9}
    container_name: guacamole-mysql
    hostname: guacamole-mysql
    volumes:
      - ${DOCKER_APP_DATA_DIR:?}/guacamole-mysql/data:/var/lib/mysql
      - ${DOCKER_APP_DATA_DIR:?}/guacamole-mysql/init:/docker-entrypoint-initdb.d:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      <<: *guacamole-mysql-environment
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?}

  guacd:
    extends:
      file: ../service-defaults.yaml
      service: service-defaults
    image: ${GUACD_IMAGE:-guacamole/guacd}:${GUACD_IMAGE_TAG:-latest}
    container_name: guacd
    hostname: guacd
    volumes:
      - /etc/localtime:/etc/localtime:ro

  guacamole:
    extends:
      file: ../service-defaults.yaml
      service: service-defaults
    image: ${GUACAMOLE_IMAGE:-guacamole/guacamole}:${GUACAMOLE_IMAGE_TAG:-latest}
    container_name: guacamole
    hostname: guacamole
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      <<: *guacamole-mysql-environment
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: guacamole-mysql
    depends_on:
      - guacamole-mysql
      - guacd
    labels:
      - traefik.enable=true
      - traefik.http.routers.guacamole.entryPoints=websecure
      - traefik.http.routers.guacamole.rule=Host(`guacamole.${DOMAIN_NAME:?}`)
      - traefik.http.services.guacamole.loadBalancer.server.port=8080
