networks:
  proxy:
    external: true
  default:

services:

  guacamole-postgres:
    image: ${POSTGRES_IMAGE:-postgres}:${POSTGRES_IMAGE_TAG:-17}
    container_name: guacamole-postgres
    hostname: guacamole-postgres
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - default
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
      - ${DOCKER_APP_DATA_DIR:?}/guacamole/postgres/data:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      PGDATA: /data/pgdata
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      POSTGRES_USER: guacamole_user
      POSTGRES_DB: guacamole_db

  guacd:
    image: ${GUACD_IMAGE:-guacamole/guacd}:${GUACD_IMAGE_TAG:-latest}
    container_name: guacd
    hostname: guacd
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - default
    volumes:
      - /etc/localtime:/etc/localtime:ro

  guacamole:
    image: ${GUACAMOLE_IMAGE:-guacamole/guacamole}:${GUACAMOLE_IMAGE_TAG:-latest}
    container_name: guacamole
    hostname: guacamole
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - default
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRESQL_HOSTNAME: guacamole-postgres
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_USER: guacamole_user
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD:?}
    depends_on:
      - guacamole-postgres
      - guacd
    labels:
      - traefik.http.middlewares.guacamole-add-prefix-mdw.addPrefix.prefix=/guacamole
      - traefik.http.routers.guacamole-rtr.middlewares=guacamole-add-prefix-mdw@docker
      - traefik.http.routers.guacamole-rtr.rule=Host(`guacamole.${DOMAIN_NAME:?}`)
      - traefik.http.services.guacamole-svc.loadBalancer.server.port=8080
