x-guacamaole-mysql-environment: &guacamaole-mysql-environment
  MYSQL_DATABASE: guacamole_db
  MYSQL_PASSWORD: ${MYSQL_PASSWORD:?}
  MYSQL_USER: guacamole_user

services:

  guacamole-mysql:
    image: mysql
    container_name: guacamole-mysql
    hostname: guacamole-mysql
    restart: unless-stopped
    volumes:
      - ${DOCKER_APP_DATA_DIR:?}/guacamole-mysql/data:/var/lib/mysql
      - ${DOCKER_APP_DATA_DIR:?}/guacamole-mysql/init:/docker-entrypoint-initdb.d:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      <<: *guacamaole-mysql-environment
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?}

  guacd:
    image: guacamole/guacd:latest
    container_name: guacd
    hostname: guacd
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro

  guacamole:
    image: guacamole/guacamole:latest
    container_name: guacamole
    hostname: guacamole
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      <<: *guacamaole-mysql-environment
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: guacamole-mysql
    depends_on:
      - guacamole-mysql
      - guacd
    labels:
      - traefik.enable=true
      - traefik.http.routers.guacamole.entryPoints=websecure
      - traefik.http.routers.guacamole.rule=Host(`guacamole.${DOMAIN_NAME:?}`)
