#!/usr/bin/env bash

set -euo pipefail

readonly guacamole_postgres_init_dir="${DOCKER_APP_DATA_DIR}/guacamole/postgres/init"
readonly guacamole_postgres_init_file="${guacamole_postgres_init_dir}/init-db.sql"
mkdir --parents "${guacamole_postgres_init_dir}"
if [[ ! -f "${guacamole_postgres_init_file}" ]]; then
  docker run --rm guacamole/guacamole:latest /opt/guacamole/bin/initdb.sh --postgresql > "${guacamole_postgres_init_file}"
fi
