networks:
  proxy:
    external: true

volumes:
  speedtest-tracker-config:

services:
  speedtest-tracker:
    image: ${SPEEDTEST_TRACKER_IMAGE:-lscr.io/linuxserver/speedtest-tracker}:${SPEEDTEST_TRACKER_IMAGE_TAG:-latest}
    container_name: speedtest-tracker
    hostname: speedtest-tracker
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - speedtest-tracker-config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      PUID: ${PUID:?}
      PGID: ${PGID:?}
      TZ: ${DOCKER_TZ:?}
      APP_KEY: ${APP_KEY:?}
      APP_URL: https://speedtest-tracker.${DOMAIN_NAME:?}
      DB_CONNECTION: sqlite
      PRUNE_RESULTS_OLDER_THAN: 30
      SPEEDTEST_SCHEDULE: ${SPEEDTEST_SCHEDULE:-22 * * * *}
      SPEEDTEST_SERVERS: ${SPEEDTEST_SERVERS:-35058,23094,51330}
    labels:
      - traefik.docker.network=proxy
      - traefik.enable=true
      - traefik.http.routers.speedtest-tracker-rtr.entryPoints=websecure
      - traefik.http.routers.speedtest-tracker-rtr.middlewares=default-chain-mdw@file
      - traefik.http.routers.speedtest-tracker-rtr.rule=Host(`speedtest-tracker.${DOMAIN_NAME:?}`)
      - traefik.http.services.speedtest-tracker-svc.loadBalancer.server.port=80
