include:
  - ../traefik-proxy-network.yaml

services:
  speedtest-tracker:
    extends:
      file: ../service-defaults.yaml
      service: service-defaults
    image: ${SPEEDTEST_TRACKER_IMAGE:-lscr.io/linuxserver/speedtest-tracker}:${SPEEDTEST_TRACKER_IMAGE_TAG:-latest}
    container_name: speedtest-tracker
    hostname: speedtest-tracker
    volumes:
      - ${DOCKER_APP_DATA_DIR:?}/speedtest-tracker:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      APP_KEY: ${APP_KEY:?}
      APP_URL: http://speedtest-tracker.${DOMAIN_NAME:?}
      DB_CONNECTION: sqlite
      PRUNE_RESULTS_OLDER_THAN: 30
      SPEEDTEST_SCHEDULE: ${SPEEDTEST_SCHEDULE:-22 * * * *}
      SPEEDTEST_SERVERS: ${SPEEDTEST_SERVERS:-35058,23094,51330}
      TZ: ${TZ:?}
    labels:
      - traefik.enable=true
      - traefik.http.routers.speedtest-tracker.entryPoints=websecure
      - traefik.http.routers.speedtest-tracker.rule=Host(`speedtest-tracker.${DOMAIN_NAME:?}`)
