#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${DOCKER_COMPOSE_DIR}/functions.bash"

env_file="$(env_file)"
set_env_file_var_if_not_defined "${env_file}" 'APP_KEY' 'https://speedtest-tracker.dev/'
