#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${DOCKER_COMPOSE_DIR}/functions.bash"

env_file="$(env_file)"
if ! file_exists "${env_file}"; then
  cp "${env_file}.template" "${env_file}"
fi

set_env_file_var_if_not_defined "${env_file}" 'APP_KEY' 'https://speedtest-tracker.dev/'
