#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${DOCKER_COMPOSE_DIR}/functions.bash"

readonly app_data_dir="${DOCKER_APP_DATA_DIR}/speedtest-tracker"
create_dir_or_change_ownership "${app_data_dir}"

readonly env_file="$(env_file)"
set_env_file_var_if_not_defined "${env_file}" 'APP_KEY' 'https://speedtest-tracker.dev/'
