networks:
  proxy:
    external: true

services:
  dumbwhois:
    image: dumbwareio/dumbwhois:latest
    container_name: dumbwhois
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.dumbwhois-rtr.rule=Host(`dumbwhois.${DOMAIN_NAME:?}`)
      - traefik.http.services.dumbwhois-svc.loadBalancer.server.port=3000
