networks:
  proxy:
    external: true
  traefik-socket-proxy:
    name: traefik-socket-proxy

services:

  traefik-socket-proxy:
    image: ${SOCKET_PROXY_IMAGE:-lscr.io/linuxserver/socket-proxy}:${SOCKET_PROXY_IMAGE_TAG:-latest}
    container_name: traefik-socket-proxy
    hostname: traefik-socket-proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /run
    networks:
      - traefik-socket-proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_SOCKET:?}:/var/run/docker.sock
    environment:
      CONTAINERS: 1

  traefik:
    image: ${TRAEFIK_IMAGE:-traefik}:${TRAEFIK_IMAGE_TAG:-v3}
    container_name: traefik
    hostname: traefik
    restart: unless-stopped
    user: ${PUID:?}:${PGID:?}
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - traefik-socket-proxy
    depends_on:
      - traefik-socket-proxy
    ports:
      - "${TAILNET_IP:?}:80:80"
      - "${TAILNET_IP:?}:443:443"
      - "${TAILNET_IP:?}:${DASHBOARD_PORT:-8080}:8080"
    volumes:
      - ${DOCKER_APP_DATA_DIR:?}/traefik:/etc/traefik/certs
      - ./conf:/etc/traefik/conf:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: ${DOCKER_TZ:?}
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN:?}
      DOMAIN_NAME: ${DOMAIN_NAME:?}
    command:
      - --accessLog.filters.statusCodes=${ACCESS_LOG_STATUS_CODES:-400-499,500-599}
      - --api.dashboard=true
      - --api.disableDashboardAd=true
      - --global.sendAnonymousUsage=true
      - --experimental.fastProxy
      - --log.level=${LOG_LEVEL:-INFO}
      - --certificatesResolvers.dns-cloudflare.acme.caServer=${ACME_CA_SERVER:-https://acme-v02.api.letsencrypt.org/directory}
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.resolvers=1.1.1.1:53,8.8.8.8:53
      - --certificatesResolvers.dns-cloudflare.acme.storage=/etc/traefik/certs/cloudflare-acme.json
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls.certresolver=dns-cloudflare
      - --entrypoints.websecure.http.tls.domains[0].main=${DOMAIN_NAME:?}
      - --entrypoints.websecure.http.tls.domains[0].sans=*.${DOMAIN_NAME:?}
      - --providers.docker.endpoint=tcp://traefik-socket-proxy:2375
      - --providers.docker.exposedByDefault=${DOCKER_EXPOSED_BY_DEFAULT:-false}
      - --providers.file.directory=/etc/traefik/conf
      - --providers.file.watch=true
    labels:
      - traefik.docker.network=proxy
      - traefik.enable=true
      - traefik.http.routers.traefik-rtr.entryPoints=websecure
      - traefik.http.routers.traefik-rtr.middlewares=default-chain-mdw@file
      - traefik.http.routers.traefik-rtr.rule=Host(`traefik.${DOMAIN_NAME:?}`)
      - traefik.http.routers.traefik-rtr.service=api@internal
