networks:
  proxy:
    external: true
  traefik-socket-proxy:

services:

  traefik-socket-proxy:
    image: ${SOCKET_PROXY_IMAGE:-tecnativa/docker-socket-proxy}:${SOCKET_PROXY_IMAGE_TAG:-latest}
    container_name: traefik-socket-proxy
    hostname: traefik-socket-proxy
    privileged: true
    restart: unless-stopped
    networks:
      - traefik-socket-proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_SOCKET:?}:/var/run/docker.sock
    environment:
      LOG_LEVEL: ${SOCKET_PROXY_LOG_LEVEL:-debug}
      CONTAINERS: 1

  traefik:
    image: ${TRAEFIK_IMAGE:-traefik}:${TRAEFIK_IMAGE_TAG:-v3}
    container_name: traefik
    hostname: traefik
    restart: unless-stopped
    networks:
      - proxy
      - traefik-socket-proxy
    ports:
      - "${TAILNET_IP:?}:80:80"
      - "${TAILNET_IP:?}:443:443"
      - "${TAILNET_IP:?}:${DASHBOARD_PORT:-8080}:8080"
    volumes:
      - ${DOCKER_APP_DATA_DIR:?}/traefik:/etc/traefik/certs
      - ./conf:/etc/traefik/conf:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: ${DOCKER_TZ:?}
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN:?}
      DOMAIN_NAME: ${DOMAIN_NAME:?}
    command:
      ## TODO check on access logging - check on stdout
      # TODO figure out which statuses to keep in logging
      # 2xx - successful
      # 3xx - redirection
      # 4xx - client error
      # 5xx - server error
      - --accessLog.filters.statusCodes=${ACCESS_LOG_STATUS_CODES:-200-299,300-399,400-499,500-599}
      - --api.dashboard=true
      - --api.disableDashboardAd=true
      - --global.sendAnonymousUsage=true
      - --log.level=${LOG_LEVEL:-INFO}
      ## TODO non-staging server -- see if removing caServer config uses prod url
      - --certificatesResolvers.dns-cloudflare.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      ## TODO put CA SERVER stuff in .env.template with default value of staging server
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.resolvers=1.1.1.1:53,8.8.8.8:53
      - --certificatesResolvers.dns-cloudflare.acme.storage=/etc/traefik/certs/cloudflare-acme.json
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls.certresolver=dns-cloudflare
      - --entrypoints.websecure.http.tls.domains[0].main=${DOMAIN_NAME:?}
      - --entrypoints.websecure.http.tls.domains[0].sans=*.${DOMAIN_NAME:?}
      ## TODO this is config necessary?
#      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.endpoint=tcp://traefik-socket-proxy:2375
      - --providers.docker.exposedByDefault=${DOCKER_EXPOSED_BY_DEFAULT:-false}
      - --providers.file.directory=/etc/traefik/conf
      - --providers.file.watch=true
