#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${DOCKER_DIR}/scripts/functions.bash"

env_file="$(env_file)"
readonly env_file
if ! file_exists "${env_file}"; then
  cp "${env_file}.template" "${env_file}"
fi

set_var 'AUTHELIA_DUO_API_HOSTNAME' 'https://admin-185050d5.duosecurity.com/applications'
set_var 'AUTHELIA_DUO_INTEGRATION_KEY' 'https://admin-185050d5.duosecurity.com/applications'
set_var 'AUTHELIA_DUO_SECRET_KEY' 'https://admin-185050d5.duosecurity.com/applications'
set_var 'AUTHELIA_SESSION_ENCRYPTION_KEY' 'pwgen --secure --num-passwords 1 64'
set_var 'AUTHELIA_STORAGE_ENCRYPTION_KEY' 'pwgen --secure --num-passwords 1 64'
set_var 'CROWDSEC_BOUNCER_API_KEY' 'pwgen --secure --num-passwords 1 64'
set_var 'CROWDSEC_ENGINE_ENROLL_KEY' 'https://app.crowdsec.net/security-engines'
set_var 'MAXMIND_ID'
set_var 'MAXMIND_KEY'
set_var 'REDIS_PASSWORD' 'pwgen --secure --num-passwords 1 64'
set_var 'TRAEFIK_CF_DNS_API_TOKEN' 'https://dash.cloudflare.com/profile/api-tokens - Zone/Zone/Read and Zone/DNS/Edit permissions'

authelia_notifications_file="$(this_script_dir)/authelia-notifications.txt"
write_file_if_not_exists "${authelia_notifications_file}"

crowdsec_bouncer_api_key="$(get_var 'CROWDSEC_BOUNCER_API_KEY')"
crowdsec_engine_enroll_key="$(get_var 'CROWDSEC_ENGINE_ENROLL_KEY')"
log "Run this after starting proxy stack (if not already run):
> docker exec 'crowdsec' cscli bouncers add 'traefik-crowdsec-bouncer' --key '${crowdsec_bouncer_api_key}' && docker exec 'crowdsec' cscli console enroll -e context --name '${DOMAIN_NAME}' '${crowdsec_engine_enroll_key}'"
