#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"

if container_is_running 'crowdsec'; then
  log 'Running CrowdSec hub update and upgrade'
  docker exec 'crowdsec' cscli hub update
  docker exec 'crowdsec' cscli hub upgrade
  log 'Ran CrowdSec hub update and upgrade'
fi
