#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${DOCKER_DIR}/compose/init-scripts-common.bash"

copy_env_file_template

prompt_set_env_file_val 'POSTGRES_PASSWORD' "$(generate_password)"

readonly postgres_init_file="guacamole/postgres/docker-entrypoint-initdb.d/init-db.sql"
readonly postgres_init_file_content="$(docker run --rm guacamole/guacamole:latest /opt/guacamole/bin/initdb.sh --postgresql)"
write_app_data_file_if_not_exists "${postgres_init_file}" "${postgres_init_file_content}"
