#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${DOCKER_DIR}/scripts/functions.bash"

env_file="$(env_file)"
readonly env_file
if ! file_exists "${env_file}"; then
  cp "${env_file}.template" "${env_file}"
fi
function set_var() {
  set_env_file_var_if_not_defined "${env_file}" "$1" "${2:-}"
}

set_var 'POSTGRES_PASSWORD' 'pwgen --secure --num-passwords 1 64'

readonly entrypoint_path='guacamole/postgres/docker-entrypoint-initdb.d'
create_app_data_dir "${entrypoint_path}" 'guacamole/postgres/data'

readonly postgres_init_file="${DOCKER_APP_DATA_DIR}/${entrypoint_path}/init-db.sql"
readonly postgres_init_file_content="$(docker run --rm --network none guacamole/guacamole:latest /opt/guacamole/bin/initdb.sh --postgresql)"
write_app_data_file_if_not_exists "${postgres_init_file}" "${postgres_init_file_content}"
