services:
  wetty:
    image: wettyoss/wetty
    container_name: wetty
    hostname: wetty
    restart: unless-stopped
    volumes:
      - ~/.keys/id_ed25519:/id_ed25519:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      BASE: /
      SSHHOST: ${DOMAIN_NAME:?}
      SSHUSER: ${USER:?}
      SSHAUTH: publickey
      SSHKEY: /id_ed25519
      TITLE: WeTTY - ${DOMAIN_NAME:?}
    labels:
      - traefik.enable=true
      - traefik.http.routers.wetty.entryPoints=websecure
      - traefik.http.routers.wetty.rule=Host(`wetty.${DOMAIN_NAME:?}`)
