include:
  - ../defaults.yaml

services:
  wetty:
    <<: *container-defaults
    image: ${WETTY_IMAGE:-wettyoss/wetty}:${WETTY_IMAGE_TAG:latest}
    container_name: wetty
    hostname: wetty
    volumes:
      - ~/.keys/id_ed25519:/id_ed25519:ro
      - *localtime-bind
    environment:
      BASE: /
      SSHHOST: ${DOMAIN_NAME:?}
      SSHUSER: ${USER:?}
      SSHAUTH: publickey
      SSHKEY: /id_ed25519
      TITLE: WeTTY - ${DOMAIN_NAME:?}
    labels:
      - traefik.enable=true
      - traefik.http.routers.wetty.entryPoints=websecure
      - traefik.http.routers.wetty.rule=Host(`wetty.${DOMAIN_NAME:?}`)
