## TODO autorestic?
include:
  - ../traefik-proxy-network.yaml

services:
  backrest:
    extends:
      file: ../service-defaults.yaml
      service: service-defaults
    image: ${BACKREST_IMAGE:-garethgeorge/backrest}:${BACKREST_IMAGE_TAG:-latest}
    container_name: backrest
    hostname: backrest
    volumes:
      - ${DOCKER_APP_DATA_DIR:?}:/to-backup
      - ${DOCKER_APP_DATA_DIR:?}/backrest/cache:/cache
      - ${DOCKER_APP_DATA_DIR:?}/backrest/config:/config
      - ${DOCKER_APP_DATA_DIR:?}/backrest/data:/data
      - ${DOCKER_APP_DATA_DIR:?}/backrest/ssh:/root/.ssh
      - /backups/restic:/repos
      - /etc/localtime:/etc/localtime:ro
    environment:
      BACKREST_CONFIG: /config/config.json
      BACKREST_DATA: /data
      TZ: ${DOCKER_TZ:?}
      XDG_CACHE_HOME: /cache
    labels:
      - traefik.enable=true
      - traefik.http.routers.backrest.entryPoints=websecure
      - traefik.http.routers.backrest.rule=Host(`backrest.${DOMAIN_NAME:?}`)
      - traefik.http.services.backrest.loadBalancer.server.port=9898
