## TODO autorestic?
networks:
  proxy:
    external: true

services:
  backrest:
    image: ${BACKREST_IMAGE:-garethgeorge/backrest}:${BACKREST_IMAGE_TAG:-latest}
    container_name: backrest
    hostname: backrest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - ${DOCKER_APP_DATA_DIR:?}:/to-backup
      - ${DOCKER_APP_DATA_DIR:?}/backrest/cache:/cache
      - ${DOCKER_APP_DATA_DIR:?}/backrest/config:/config
      - ${DOCKER_APP_DATA_DIR:?}/backrest/data:/data
      - ${DOCKER_APP_DATA_DIR:?}/backrest/ssh:/root/.ssh
      - ${RESTIC_BACKUP_DIR:?}:/repos
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: ${DOCKER_TZ:?}
      BACKREST_CONFIG: /config/config.json
      BACKREST_DATA: /data
      XDG_CACHE_HOME: /cache
    labels:
      - traefik.docker.network=proxy
      - traefik.enable=true
      - traefik.http.routers.backrest-rtr.entryPoints=websecure
      - traefik.http.routers.backrest-rtr.middlewares=default-chain-mdw@file
      - traefik.http.routers.backrest-rtr.rule=Host(`backrest.${DOMAIN_NAME:?}`)
      - traefik.http.services.backrest-svc.loadBalancer.server.port=9898
