#!/usr/bin/env bash

set -euo pipefail

if [[ ! -d "${RESTIC_BACKUP_DIR}" ]]; then
  echo "Creating ${RESTIC_BACKUP_DIR}"
  mkdir --parents "${RESTIC_BACKUP_DIR}"
  echo "Created ${RESTIC_BACKUP_DIR}"
fi
