networks:
  proxy:
    external: true

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - ~:/srv
      - ./config.json:/.filebrowser.json
      - ${DOCKER_APP_DATA_DIR:?}/filebrowser/database:/database
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.filebrowser-rtr.rule=Host(`filebrowser.${DOMAIN_NAME:?}`)
      - traefik.http.services.filebrowser-svc.loadBalancer.server.port=80
