include:
  - ../defaults.yaml

services:
  watchtower:
    <<: *container-defaults
    image: ${WATCHTOWER_IMAGE:-containrrr/watchtower}:${WATCHTOWER_IMAGE_TAG:-latest}
    container_name: watchtower
    hostname: watchtower
    volumes:
      - *localtime-bind
      - *docker-socket-bind
    environment:
      TZ: ${TZ:?}
      WATCHTOWER_CLEANUP: ${WATCHTOWER_CLEANUP:-true}
      WATCHTOWER_DISABLE_CONTAINERS: ${WATCHTOWER_DISABLE_CONTAINERS:-}
      WATCHTOWER_INCLUDE_RESTARTING: ${WATCHTOWER_INCLUDE_RESTARTING:-true}
      WATCHTOWER_INCLUDE_STOPPED: ${WATCHTOWER_INCLUDE_STOPPED:-true}
      WATCHTOWER_NOTIFICATION_URL: discord://${DISCORD_TOKEN:?}@${DISCORD_WEBHOOK_ID:?}
      WATCHTOWER_NOTIFICATIONS: shoutrrr
      WATCHTOWER_POLL_INTERVAL: ${WATCHTOWER_POLL_INTERVAL:-86400}
      WATCHTOWER_REVIVE_STOPPED: ${WATCHTOWER_REVIVE_STOPPED:-false}
      WATCHTOWER_ROLLING_RESTART: ${WATCHTOWER_ROLLING_RESTART:-false}
      WATCHTOWER_SCHEDULE: ${WATCHTOWER_SCHEDULE:-0 0 3 * * *}
      WATCHTOWER_TIMEOUT: ${WATCHTOWER_TIMEOUT:-30s}
