services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    hostname: watchtower
    restart: unless-stopped
    user: ${PUID:?}:${PGID:?}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_SOCKET:?}:/var/run/docker.sock
    environment:
      TZ: ${TZ:?}
      WATCHTOWER_SCHEDULE: 0 0 3 * * *
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_INCLUDE_RESTARTING: true
      WATCHTOWER_INCLUDE_STOPPED: true
      WATCHTOWER_ROLLING_RESTART: false
      WATCHTOWER_TIMEOUT: 30s
      WATCHTOWER_NOTIFICATIONS: shoutrrr
      WATCHTOWER_NOTIFICATION_URL: discord://${DISCORD_TOKEN:?}@${DISCORD_WEBHOOK_ID:?}
