networks:
  socket-proxy:

services:

  watchtower-socket-proxy:
    image: ${SOCKET_PROXY_IMAGE:-tecnativa/docker-socket-proxy}:${SOCKET_PROXY_IMAGE_TAG:-latest}
    container_name: watchtower-socket-proxy
    hostname: watchtower-socket-proxy
    restart: unless-stopped
    privileged: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /run
    networks:
      - socket-proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_SOCKET:?}:/var/run/docker.sock
    environment:
      CONTAINERS: 1
      IMAGES: 1
      NETWORKS: 1
      POST: 1
      VOLUMES: 1

  watchtower:
    image: ${WATCHTOWER_IMAGE:-containrrr/watchtower}:${WATCHTOWER_IMAGE_TAG:-latest}
    container_name: watchtower
    hostname: watchtower
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - socket-proxy
    depends_on:
      - watchtower-socket-proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      DOCKER_HOST: tcp://watchtower-socket-proxy:2375
      WATCHTOWER_CLEANUP: ${WATCHTOWER_CLEANUP:-true}
      WATCHTOWER_DISABLE_CONTAINERS: ${WATCHTOWER_DISABLE_CONTAINERS:-}
      WATCHTOWER_INCLUDE_RESTARTING: ${WATCHTOWER_INCLUDE_RESTARTING:-true}
      WATCHTOWER_INCLUDE_STOPPED: ${WATCHTOWER_INCLUDE_STOPPED:-true}
      WATCHTOWER_LOG_LEVEL: ${WATCHTOWER_LOG_LEVEL:-info}
      WATCHTOWER_NO_STARTUP_MESSAGE: ${WATCHTOWER_NO_STARTUP_MESSAGE:-true}
      WATCHTOWER_NOTIFICATION_URL: discord://${DISCORD_TOKEN:?}@${DISCORD_WEBHOOK_ID:?}
      WATCHTOWER_NOTIFICATIONS: shoutrrr
      WATCHTOWER_POLL_INTERVAL: ${WATCHTOWER_POLL_INTERVAL:-86400}
      WATCHTOWER_REMOVE_VOLUMES: ${WATCHTOWER_REMOVE_VOLUMES:-true}
      WATCHTOWER_REVIVE_STOPPED: ${WATCHTOWER_REVIVE_STOPPED:-false}
      WATCHTOWER_ROLLING_RESTART: ${WATCHTOWER_ROLLING_RESTART:-false}
      WATCHTOWER_SCHEDULE: ${WATCHTOWER_SCHEDULE:-0 0 3 * * *}
      WATCHTOWER_TIMEOUT: ${WATCHTOWER_TIMEOUT:-30s}
    entrypoint: ${WATCHTOWER_ENTRY_POINT:-/watchtower}
