networks:
  proxy:
    external: true

services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - ${DOCKER_APP_DATA_DIR:?}/beszel/beszel_data:/beszel_data
      - /etc/localtime:/etc/localtime:ro
    environment:
      DISABLE_PASSWORD_AUTH: ${DISABLE_PASSWORD_AUTH:-false}
    healthcheck:
      test: /beszel health --url http://localhost:8090
    labels:
      - traefik.enable=true
      - traefik.http.routers.beszel-rtr.rule=Host(`beszel.${DOMAIN_NAME:?}`)
      - traefik.http.services.beszel-svc.loadBalancer.server.port=8090
