#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${DOCKER_DIR}/scripts/functions.bash"

env_file="$(env_file)"
readonly env_file
if ! file_exists "${env_file}"; then
  cp "${env_file}.template" "${env_file}"
fi
function set_var() {
  set_env_file_var_if_not_defined "${env_file}" "$1" "${2:-}"
}
function get_var() {
  get_env_file_defined_var "${env_file}" "$1"
}

readonly ssh_key_file="$(this_script_dir)/id_ed25519"
if ! file_exists "${ssh_key_file}"; then
  log "Generating SSH key"
  ssh-keygen -t 'ed25519' -C "beszel SSH key" -N '' -f "${ssh_key_file}"
  log "Generated SSH key"
fi
beszel_public_key="$(cat "${ssh_key_file}.pub")"
readonly beszel_public_key
set_env_file_var_to_value "${env_file}" 'BESZEL_PUBLIC_KEY' "${beszel_public_key}"

if ! pgrep -x 'beszel-agent' &> '/dev/null' &&  prompt_yn 'Install beszel-agent?'; then
    log 'Installing beszel-agent'
    curl -sL 'https://raw.githubusercontent.com/henrygd/beszel/main/supplemental/scripts/install-agent.sh' -o '/tmp/install-agent.sh'
    chmod +x '/tmp/install-agent.sh'
    /tmp/install-agent.sh -p '45876' -k "${beszel_public_key}"
    log 'Installed beszel-agent'
fi
