#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${DOCKER_DIR}/scripts/functions.bash"

env_file="$(env_file)"
readonly env_file
if ! file_exists "${env_file}"; then
  cp "${env_file}.template" "${env_file}"
fi
function set_var() {
  set_env_file_var_if_not_defined "${env_file}" "$1" "${2:-}"
}

readonly target_ssh_key_file="${DOCKER_APP_DATA_DIR}/beszel/beszel_data/id_ed25519"
if ! file_exists "${target_ssh_key_file}"; then
  log 'Generating SSH key'
  created_ssh_key_file="$(mktemp --directory)/id_ed25519"
  readonly created_ssh_key_file
  ssh-keygen -t 'ed25519' -C "beszel SSH key" -N '' -f "${created_ssh_key_file}"
  root_write_file "${target_ssh_key_file}" "$(cat "${created_ssh_key_file}")"
  root_write_file "${target_ssh_key_file}.pub" "$(cat "${created_ssh_key_file}.pub")"
  log 'Generated SSH key'
fi

beszel_public_key="$(cat "${target_ssh_key_file}.pub")"
readonly beszel_public_key
set_env_file_var_to_value "${env_file}" 'BESZEL_PUBLIC_KEY' "${beszel_public_key}"

if ! pgrep --exact 'beszel-agent' &> '/dev/null' &&  prompt_yn 'Install beszel-agent?'; then
    log 'Installing beszel-agent'
    install_agent_script="$(mktemp --direcotry)/install-agent.sh"
    readonly install_agent_script
    curl --silent --location 'https://raw.githubusercontent.com/henrygd/beszel/main/supplemental/scripts/install-agent.sh' --output "${install_agent_script}"
    chmod +x "${install_agent_script}"
    "${install_agent_script}" -p '45876' -k "${beszel_public_key}"
    log 'Installed beszel-agent'
fi
