networks:
  proxy:
    external: true

services:
  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - deunhealth.restart.on.unhealthy=true
      - traefik.enable=true
      - traefik.http.routers.it-tools-rtr.rule=Host(`it-tools.${DOMAIN_NAME:?}`)
      - traefik.http.services.it-tools-svc.loadBalancer.server.port=80
