include:
  - ../proxy-network.yaml

services:
  hello-world:
    image: crccheck/hello-world:latest
    container_name: hello-world
    hostname: hello-world
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.hello-world-rtr.entryPoints=websecure
      - traefik.http.routers.hello-world-rtr.rule=Host(`hello-world.${DOMAIN_NAME:?}`)
      - traefik.http.services.hello-world-svc.loadBalancer.server.port=8000
