networks:
  proxy:
    external: true

services:
  hello-world:
    image: crccheck/hello-world:latest
    container_name: hello-world
    hostname: hello-world
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.docker.network=proxy
      - traefik.enable=true
      - traefik.http.middlewares.hello-redirect-mdw.redirectRegex.regex=^https://hello\.(.*)
      - traefik.http.middlewares.hello-redirect-mdw.redirectRegex.replacement=https://hello-world.$${1}
      - traefik.http.routers.hello-redirect-rtr.entryPoints=websecure
      - traefik.http.routers.hello-redirect-rtr.middlewares=hello-redirect-mdw
      - traefik.http.routers.hello-redirect-rtr.rule=Host(`hello.${DOMAIN_NAME:?}`)
      - traefik.http.routers.hello-world-rtr.entryPoints=websecure
      - traefik.http.routers.hello-world-rtr.middlewares=default-chain-mdw@file
      - traefik.http.routers.hello-world-rtr.rule=Host(`hello-world.${DOMAIN_NAME:?}`)
      - traefik.http.services.hello-world-svc.loadBalancer.server.port=8000
