services:
  hello-world:
    image: crccheck/hello-world:latest
    container_name: hello-world
    hostname: hello-world
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.hello-world.entryPoints=websecure
      - traefik.http.routers.hello-world.rule=Host(`hello-world.${DOMAIN_NAME:?}`)
