networks:
  socket-proxy:

services:

  deunhealth-socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: deunhealth-socket-proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /run
    networks:
      - socket-proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_SOCKET:?}:/var/run/docker.sock
    environment:
      ALLOW_RESTARTS: 1
      CONTAINERS: 1
    healthcheck:
      test: wget --spider --quiet http://localhost:2375/version || exit 1

  deunhealth:
    image: qmcgaw/deunhealth:latest
    container_name: deunhealth
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - socket-proxy
    depends_on:
      deunhealth-socket-proxy:
        condition: service_healthy
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      DOCKER_HOST: tcp://deunhealth-socket-proxy:2375
      LOG_LEVEL: ${LOG_LEVEL:-info}
