networks:
  proxy:
    external: true

services:
  glances:
    image: ${GLANCES_IMAGE:-nicolargo/glances}:${GLANCES_IMAGE_TAG:-latest-full}
    container_name: glances
    hostname: glances
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_SOCKET:?}:/var/run/docker.sock
    environment:
      GLANCES_OPT: --webserver
    labels:
      - traefik.enable=true
      - traefik.http.routers.glances-rtr.entryPoints=websecure
      - traefik.http.routers.glances-rtr.rule=Host(`glances.${DOMAIN_NAME:?}`)
      - traefik.http.services.glances-svc.loadBalancer.server.port=61208
