networks:
  proxy:
    external: true
  socket-proxy:

services:

  glances-socket-proxy:
    image: ${SOCKET_PROXY_IMAGE:-tecnativa/docker-socket-proxy}:${SOCKET_PROXY_IMAGE_TAG:-latest}
    container_name: glances-socket-proxy
    hostname: glances-socket-proxy
    restart: unless-stopped
    privileged: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /run
    networks:
      - socket-proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_SOCKET:?}:/var/run/docker.sock
    environment:
      CONTAINERS: 1
      IMAGES: 1

  glances:
    image: ${GLANCES_IMAGE:-nicolargo/glances}:${GLANCES_IMAGE_TAG:-latest-full}
    container_name: glances
    hostname: glances
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - socket-proxy
    depends_on:
      - glances-socket-proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      DOCKER_HOST: tcp://glances-socket-proxy:2375
      GLANCES_OPT: --webserver
    labels:
      - traefik.enable=true
      - traefik.http.routers.glances-rtr.rule=Host(`glances.${DOMAIN_NAME:?}`)
      - traefik.http.services.glances-svc.loadBalancer.server.port=61208
