include:
  - ../defaults.yaml

services:
  glances:
    <<: *container-defaults
    image: ${GLANCES_IMAGE:-nicolargo/glances}:${GLANCES_IMAGE_TAG:-latest-full}
    container_name: glances
    hostname: glances
    volumes:
      - ${DOCKER_APP_DATA_DIR:?}/glances:/glances/conf/
      - *localtime-bind
      - *docker-socket-bind
    environment:
      GLANCES_OPT: --webserver
    labels:
      - traefik.enable=true
      - traefik.http.routers.glances.entryPoints=websecure
      - traefik.http.routers.glances.rule=Host(`glances.${DOMAIN_NAME:?}`)
