http:
  routers:
    cockpit-rtr:
      entryPoints:
        - websecure
      middlewares:
        - default-chain-mdw@file
      rule: 'Host(`cockpit.{{ env "DOMAIN_NAME" }}`)'
      service: cockpit-svc
  services:
    cockpit-svc:
      loadBalancer:
        servers:
          - url: 'https://{{ env "DOMAIN_NAME" }}:9090'
        serversTransport: cockpit-stx
  serversTransports:
    cockpit-stx:
      insecureSkipVerify: true
