http:
  middlewares:

    ip-allow-list-mdw:
      ipAllowList:
        sourceRange:
          - 127.0.0.1/32
          - 172.16.0.0/12
          - 100.64.0.0/10

    rate-limit-mdw:
      rateLimit:
        average: 100
        burst: 50

    secure-headers-mdw:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlMaxAge: 100
        browserXssFilter: true
        contentTypeNosniff: true
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        customResponseHeaders:
          server: ""
          X-Forwarded-Proto: "https"
          X-Robots-Tag: noarchive,noimageindex,none,nosnippet,notranslate
        #forceSTSHeader: true
        hostsProxyHeaders:
          - X-Forwarded-Host
        permissionsPolicy: camera=(), geolocation=(), microphone=(), payment=(), usb=(), vr=()
        referrerPolicy: same-origin
        sslProxyHeaders:
          X-Forwarded-Proto: https
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 63072000

    auth-mdw:
      forwardauth:
        address: http://authelia:9091/api/verify?rd=https://authelia.{{ env "DOMAIN_NAME" }}/
        authResponseHeaders:
          - Remote-Email
          - Remote-Groups
          - Remote-Name
          - Remote-User
        trustForwardHeader: true

    auth-basic-mdw:
      forwardauth:
        address: http://auth:9091/api/verify?auth=basic
        authResponseHeaders:
          - Remote-Email
          - Remote-Groups
          - Remote-Name
          - Remote-User
        trustForwardHeader: true

    default-chain-mdw:
      chain:
        middlewares:
          - ip-allow-list-mdw@file
          - rate-limit-mdw@file
          - secure-headers-mdw@file
