networks:
  proxy:
    external: true

services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - ~/Code:/code
      - ./run-override:/etc/s6-overlay/s6-rc.d/init-mod-code-server-extension-arguments/run:ro
      - ${DOCKER_APP_DATA_DIR:?}/code-server/config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      PUID: ${PUID:?}
      PGID: ${PGID:?}
      DEFAULT_WORKSPACE: /code
      DOCKER_MODS: linuxserver/mods:code-server-extension-arguments
      PROXY_DOMAIN: code-server.${DOMAIN_NAME:?}
      VSCODE_EXTENSION_IDS: >
        | alefragnani.Bookmarks
        | alefragnani.project-manager
        | christian-kohler.path-intellisense
        | chrmarti.regex
        | donjayamanne.githistory
        | DontShaveTheYak.groovy-guru
        | eamodio.gitlens
        | esbenp.prettier-vscode
        | formulahendry.auto-close-tag
        | formulahendry.auto-rename-tag
        | foxundermoon.shell-format
        | Gruntfuggly.todo-tree
        | humao.rest-client
        | jakob101.RelativePath
        | mads-hartmann.bash-ide-vscode
        | mohsen1.prettify-json
        | ms-azuretools.vscode-docker
        | ms-vscode-remote.remote-ssh
        | naumovs.color-highlight
        | NicolasVuillamy.vscode-groovy-lint
        | oderwat.indent-rainbow
        | PascalReitermann93.vscode-yaml-sort
        | pinage404.bash-extension-pack
        | redhat.java
        | redhat.vscode-yaml
        | rogalmic.bash-debug
        | scalameta.metals
        | sdras.night-owl
        | Shan.code-settings-sync
        | SonarSource.sonarlint-vscode
        | streetsidesoftware.code-spell-checker
        | stylelint.vscode-stylelint
        | usernamehw.errorlens
        | VisualStudioExptTeam.vscodeintellicode
        | vscjava.vscode-java-dependency
        | vscjava.vscode-java-pack
        | vscjava.vscode-maven
        | vscode-icons-team.vscode-icons
        | wayou.vscode-todo-highlight
        | yzhang.markdown-all-in-one
    labels:
      - deunhealth.restart.on.unhealthy=true
      - traefik.enable=true
      - traefik.http.routers.code-server-rtr.rule=Host(`code-server.${DOMAIN_NAME:?}`)
      - traefik.http.services.code-server-svc.loadBalancer.server.port=8443
