networks:
  proxy:
    external: true
  socket-proxy:

volumes:
  authelia-config:
  crowdsec-config:
  crowdsec-data:
  traefik-certs:

services:

  authelia:
    image: ${AUTHELIA_IMAGE:-authelia/authelia}:${AUTHELIA_IMAGE_TAG:-latest}
    container_name: authelia
    hostname: authelia
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - ./authelia-notifications.txt:/notifications.txt
      - ./authelia/config.yaml:/config.yaml:ro
      - ./authelia/users.yaml:/users.yaml:ro
      - /var/log/authelia:/var/log/authelia
      - authelia-config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME:?}
      DUO_API_HOSTNAME: ${AUTHELIA_DUO_API_HOSTNAME:?}
      DUO_INTEGRATION_KEY: ${AUTHELIA_DUO_INTEGRATION_KEY:?}
      DUO_SECRET_KEY: ${AUTHELIA_DUO_SECRET_KEY:?}
      STORAGE_ENCRYPTION_KEY: ${AUTHELIA_STORAGE_ENCRYPTION_KEY:?}
      LOG_LEVEL: ${AUTHELIA_LOG_LEVEL:-info}
      X_AUTHELIA_CONFIG: /config.yaml
      X_AUTHELIA_CONFIG_FILTERS: template
    labels:
      - traefik.enable=true
      - traefik.http.routers.authelia-rtr.entryPoints=websecure
      - traefik.http.routers.authelia-rtr.middlewares=default-chain-no-auth-mdw@file
      - traefik.http.routers.authelia-rtr.rule=Host(`authelia.${DOMAIN_NAME:?}`)
      - traefik.http.routers.authelia-rtr.tls=true
      - traefik.http.services.authelia-svc.loadBalancer.server.port=9091

  crowdsec:
    image: ${CROWDSEC_IMAGE:-crowdsecurity/crowdsec}:${CROWDSEC_IMAGE_TAG:-latest}
    container_name: crowdsec
    hostname: crowdsec
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      ## TODO do any of these need to be readonly?
      - ./crowdsec/acquis:/etc/crowdsec/acquis.d:ro
      - ./crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml:ro
      - ./crowdsec/config.yaml:/etc/crowdsec/config.yaml.local:ro
      - crowdsec-config:/etc/crowdsec
      - crowdsec-data:/var/lib/crowdsec/data
      - /var/log/authelia:/var/log/external/authelia:ro
      - /var/log/traefik:/var/log/external/traefik:ro
      - /var/log/auth.log:/var/log/external/auth.log:ro
      - /var/log/kern.log:/var/log/external/kern.log:ro
      - /var/log/syslog:/var/log/external/syslog:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      COLLECTIONS: >
        crowdsecurity/appsec-crs
        crowdsecurity/appsec-generic-rules
        crowdsecurity/appsec-virtual-patching
        crowdsecurity/base-http-scenarios
        crowdsecurity/http-cve
        crowdsecurity/http-dos
        crowdsecurity/iptables
        crowdsecurity/linux
        crowdsecurity/linux-lpe
        crowdsecurity/sshd
        crowdsecurity/traefik
        LePresidente/authelia
        ${CROWDSEC_EXTRA_COLLECTIONS:-}

  ## TODO dashboard? -- https://github.com/crowdsecurity/example-docker-compose/blob/main/basic/docker-compose.yml

  crowdsec-bouncer:
    image: ${CROWDSEC_BOUNCER_IMAGE:-docker.io/fbonalair/traefik-crowdsec-bouncer}:${CROWDSEC_BOUNCER_IMAGE_TAG:-latest}
    container_name: crowdsec-bouncer
    hostname: crowdsec-bouncer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    depends_on:
      - crowdsec
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      CROWDSEC_AGENT_HOST: crowdsec:8080
      CROWDSEC_BOUNCER_API_KEY: ${CROWDSEC_BOUNCER_API_KEY:?}
      CROWDSEC_BOUNCER_LOG_LEVEL: ${CROWDSEC_BOUNCER_LOG_LEVEL:-info}
      GIN_MODE: ${GIN_MODE:-release}

  traefik-socket-proxy:
    image: ${SOCKET_PROXY_IMAGE:-lscr.io/linuxserver/socket-proxy}:${SOCKET_PROXY_IMAGE_TAG:-latest}
    container_name: traefik-socket-proxy
    hostname: socket-proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /run
    networks:
      - socket-proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_SOCKET:?}:/var/run/docker.sock
    environment:
      CONTAINERS: 1

  traefik-stdout-logger:
    image: ${TRAEFIK_STDOUT_LOGGER_IMAGE:-alpine}:${TRAEFIK_STDOUT_LOGGER_IMAGE_TAG:-latest}
    container_name: traefik-stdout-logger
    hostname: traefik-stdout-logger
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/log/traefik:/var/log/traefik:ro
      - /etc/localtime:/etc/localtime:ro
    command: tail -q -n 0 -F /var/log/traefik/traefik.log /var/log/traefik/access.log

  traefik:
    image: ${TRAEFIK_IMAGE:-traefik}:${TRAEFIK_IMAGE_TAG:-v3}
    container_name: traefik
    hostname: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - socket-proxy
    depends_on:
      - authelia
      - crowdsec-bouncer
      - traefik-socket-proxy
      - traefik-stdout-logger
    ports:
      - "${TAILNET_IP:?}:80:80"
      - "${TAILNET_IP:?}:443:443"
      - "${TAILNET_IP:?}:${TRAEFIK_DASHBOARD_PORT:-8080}:8080"
    volumes:
      - ./traefik:/etc/traefik/conf:ro
      - /var/log/traefik:/var/log/traefik
      - traefik-certs:/etc/traefik/certs
      - /etc/localtime:/etc/localtime:ro
    environment:
      CF_DNS_API_TOKEN: ${TRAEFIK_CF_DNS_API_TOKEN:?}
      DOMAIN_NAME: ${DOMAIN_NAME:?}
    command:
      - --accessLog.filePath=/var/log/traefik/access.log
      - --accessLog.filters.statusCodes=${TRAEFIK_ACCESS_LOG_STATUS_CODES:-400-499,500-599}
      - --api.dashboard=true
      - --api.disableDashboardAd=true
      - --global.sendAnonymousUsage=true
      - --experimental.fastProxy
      - --log.filePath=/var/log/traefik/traefik.log
      - --log.level=${TRAEFIK_LOG_LEVEL:-INFO}
      - --certificatesResolvers.dns-cloudflare.acme.caServer=${TRAEFIK_ACME_CA_SERVER:-https://acme-v02.api.letsencrypt.org/directory}
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.resolvers=1.1.1.1:53,8.8.8.8:53
      - --certificatesResolvers.dns-cloudflare.acme.storage=/etc/traefik/certs/cloudflare-acme.json
      - --entrypoints.web.address=:80
      - --entryPoints.web.forwardedHeaders.trustedIPs=${TRAEFIK_TRUSTED_IPS:-127.0.0.1/32,100.64.0.0/10}
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.websecure.address=:443
      - --entryPoints.websecure.forwardedHeaders.trustedIPs=${TRAEFIK_TRUSTED_IPS:-127.0.0.1/32,100.64.0.0/10}
      - --entrypoints.websecure.http.tls.certresolver=dns-cloudflare
      - --entrypoints.websecure.http.tls.domains[0].main=${DOMAIN_NAME:?}
      - --entrypoints.websecure.http.tls.domains[0].sans=*.${DOMAIN_NAME:?}
      - --providers.docker.endpoint=tcp://traefik-socket-proxy:2375
      - --providers.docker.exposedByDefault=${TRAEFIK_DOCKER_EXPOSED_BY_DEFAULT:-false}
      - --providers.docker.network=proxy
      - --providers.file.directory=/etc/traefik/conf
      - --providers.file.watch=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-rtr.entryPoints=websecure
      - traefik.http.routers.traefik-rtr.middlewares=default-chain-with-auth-mdw@file
      - traefik.http.routers.traefik-rtr.rule=Host(`traefik.${DOMAIN_NAME:?}`)
      - traefik.http.routers.traefik-rtr.tls=true
      - traefik.http.routers.traefik-rtr.service=api@internal
