networks:
  proxy:
    external: true
  socket-proxy:

volumes:
  traefik-certs:
  authelia-config:

services:

  authelia:
    image: ${AUTHELIA_IMAGE:-authelia/authelia}:${AUTHELIA_IMAGE_TAG:-latest}
    container_name: authelia
    hostname: authelia
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - ./authelia-notifications.txt:/notifications.txt
      - ./authelia/config.yaml:/config.yaml:ro
      - ./authelia/users.yaml:/users.yaml:ro
      - authelia-config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME:?}
      DUO_API_HOSTNAME: ${AUTHELIA_DUO_API_HOSTNAME:?}
      DUO_INTEGRATION_KEY: ${AUTHELIA_DUO_INTEGRATION_KEY:?}
      DUO_SECRET_KEY: ${AUTHELIA_DUO_SECRET_KEY:?}
      STORAGE_ENCRYPTION_KEY: ${AUTHELIA_STORAGE_ENCRYPTION_KEY:?}
      LOG_LEVEL: ${AUTHELIA_LOG_LEVEL:-info}
      RVENUTOLO_EMAIL: ${AUTHELIA_RVENUTOLO_EMAIL:?}
      RVENUTOLO_PASSWORD_HASH: ${AUTHELIA_RVENUTOLO_PASSWORD_HASH:?}
      X_AUTHELIA_CONFIG: /config.yaml
      X_AUTHELIA_CONFIG_FILTERS: template
    labels:
      - traefik.enable=true
      - traefik.http.routers.authelia-rtr.entryPoints=websecure
      - traefik.http.routers.authelia-rtr.middlewares=default-chain-no-auth-mdw@file
      - traefik.http.routers.authelia-rtr.rule=Host(`authelia.${DOMAIN_NAME:?}`)
      - traefik.http.routers.authelia-rtr.tls=true
      - traefik.http.services.authelia-svc.loadBalancer.server.port=9091

  traefik-socket-proxy:
    image: ${SOCKET_PROXY_IMAGE:-lscr.io/linuxserver/socket-proxy}:${SOCKET_PROXY_IMAGE_TAG:-latest}
    container_name: traefik-socket-proxy
    hostname: socket-proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /run
    networks:
      - socket-proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_SOCKET:?}:/var/run/docker.sock
    environment:
      CONTAINERS: 1

  traefik:
    image: ${TRAEFIK_IMAGE:-traefik}:${TRAEFIK_IMAGE_TAG:-v3}
    container_name: traefik
    hostname: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - socket-proxy
    depends_on:
      - traefik-socket-proxy
      - authelia
    ports:
      - "${TAILNET_IP:?}:80:80"
      - "${TAILNET_IP:?}:443:443"
      - "${TAILNET_IP:?}:${TRAEFIK_DASHBOARD_PORT:-8080}:8080"
    volumes:
      - ./traefik:/etc/traefik/conf:ro
      - traefik-certs:/etc/traefik/certs
      - /etc/localtime:/etc/localtime:ro
    environment:
      CF_DNS_API_TOKEN: ${TRAEFIK_CF_DNS_API_TOKEN:?}
      DOMAIN_NAME: ${DOMAIN_NAME:?}
    command:
      - --accessLog.filters.statusCodes=${TRAEFIK_ACCESS_LOG_STATUS_CODES:-400-499,500-599}
      - --api.dashboard=true
      - --api.disableDashboardAd=true
      - --global.sendAnonymousUsage=true
      - --experimental.fastProxy
      - --log.level=${TRAEFIK_LOG_LEVEL:-INFO}
      - --certificatesResolvers.dns-cloudflare.acme.caServer=${TRAEFIK_ACME_CA_SERVER:-https://acme-v02.api.letsencrypt.org/directory}
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.resolvers=1.1.1.1:53,8.8.8.8:53
      - --certificatesResolvers.dns-cloudflare.acme.storage=/etc/traefik/certs/cloudflare-acme.json
      - --entrypoints.web.address=:80
      - --entryPoints.web.forwardedHeaders.trustedIPs=${TRAEFIK_TRUSTED_IPS:-127.0.0.1/32,100.64.0.0/10}
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.websecure.address=:443
      - --entryPoints.websecure.forwardedHeaders.trustedIPs=${TRAEFIK_TRUSTED_IPS:-127.0.0.1/32,100.64.0.0/10}
      - --entrypoints.websecure.http.tls.certresolver=dns-cloudflare
      - --entrypoints.websecure.http.tls.domains[0].main=${DOMAIN_NAME:?}
      - --entrypoints.websecure.http.tls.domains[0].sans=*.${DOMAIN_NAME:?}
      - --providers.docker.endpoint=tcp://traefik-socket-proxy:2375
      - --providers.docker.exposedByDefault=${TRAEFIK_DOCKER_EXPOSED_BY_DEFAULT:-false}
      - --providers.docker.network=proxy
      - --providers.file.directory=/etc/traefik/conf
      - --providers.file.watch=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-rtr.entryPoints=websecure
      - traefik.http.routers.traefik-rtr.middlewares=default-chain-with-auth-mdw@file
      - traefik.http.routers.traefik-rtr.rule=Host(`traefik.${DOMAIN_NAME:?}`)
      - traefik.http.routers.traefik-rtr.tls=true
      - traefik.http.routers.traefik-rtr.service=api@internal
