#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${DOCKER_COMPOSE_DIR}/functions.bash"

env_file="$(env_file)"
set_env_file_var_if_not_defined "${env_file}" 'AUTHELIA_DUO_API_HOSTNAME' 'https://admin-185050d5.duosecurity.com/applications'
set_env_file_var_if_not_defined "${env_file}" 'AUTHELIA_DUO_INTEGRATION_KEY' 'https://admin-185050d5.duosecurity.com/applications'
set_env_file_var_if_not_defined "${env_file}" 'AUTHELIA_DUO_SECRET_KEY' 'https://admin-185050d5.duosecurity.com/applications'
set_env_file_var_if_not_defined "${env_file}" 'AUTHELIA_SESSION_ENCRYPTION_KEY' 'docker run --rm authelia/authelia:latest authelia crypto rand --length 64 --charset alphanumeric'
set_env_file_var_if_not_defined "${env_file}" 'AUTHELIA_STORAGE_ENCRYPTION_KEY' 'docker run --rm authelia/authelia:latest authelia crypto rand --length 64 --charset alphanumeric'
set_env_file_var_if_not_defined "${env_file}" 'CROWDSEC_BOUNCER_API_KEY' 'docker run --rm authelia/authelia:latest authelia crypto rand --length 64 --charset alphanumeric'
set_env_file_var_if_not_defined "${env_file}" 'CROWDSEC_ENGINE_ENROLL_KEY' 'https://app.crowdsec.net/security-engines'
set_env_file_var_if_not_defined "${env_file}" 'TRAEFIK_CF_DNS_API_TOKEN' 'https://dash.cloudflare.com/profile/api-tokens - Zone/Zone/Read and Zone/DNS/Edit permissions'

authelia_notifications_file="$(this_script_dir)/authelia-notifications.txt"
write_file_if_not_exists "${authelia_notifications_file}"

root_copy_file "$(this_script_dir)/crowdsec/cron-crowdsec-hub-update-upgrade" '/etc/cron.d/crowdsec-hub-update-upgrade'

crowdsec_bouncer_api_key="$(get_env_file_defined_var "${env_file}" 'CROWDSEC_BOUNCER_API_KEY')"
crowdsec_engine_enroll_key="$(get_env_file_defined_var "${env_file}" 'CROWDSEC_ENGINE_ENROLL_KEY')"
log "Run this after starting proxy stack (if not already run):
> docker exec 'crowdsec' cscli bouncers add 'traefik-crowdsec-bouncer' --key '${crowdsec_bouncer_api_key}' && docker exec 'crowdsec' cscli console enroll -e context --name '${DOMAIN_NAME}' '${crowdsec_engine_enroll_key}'"
