#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${DOCKER_COMPOSE_DIR}/functions.bash"

readonly env_file="$(env_file)"
set_env_file_var_if_not_defined "${env_file}" 'AUTHELIA_DUO_API_HOSTNAME' 'https://admin-185050d5.duosecurity.com/applications'
set_env_file_var_if_not_defined "${env_file}" 'AUTHELIA_DUO_INTEGRATION_KEY' 'https://admin-185050d5.duosecurity.com/applications'
set_env_file_var_if_not_defined "${env_file}" 'AUTHELIA_DUO_SECRET_KEY' 'https://admin-185050d5.duosecurity.com/applications'
set_env_file_var_if_not_defined "${env_file}" 'AUTHELIA_STORAGE_ENCRYPTION_KEY' 'docker run --rm authelia/authelia:latest authelia crypto rand --length 64 --charset alphanumeric'
set_env_file_var_if_not_defined "${env_file}" 'TRAEFIK_CROWDSEC_BOUNCER_API_KEY' 'docker compose exec crowdsec cscli bouncers add traefik-crowdsec-bouncer'
set_env_file_var_if_not_defined "${env_file}" 'TRAEFIK_CF_DNS_API_TOKEN' 'https://dash.cloudflare.com/profile/api-tokens - Zone/Zone/Read and Zone/DNS/Edit permissions'

readonly authelia_notifications_file="$(this_script_dir)/authelia-notifications.txt"
create_file_if_not_exists "${authelia_notifications_file}"
