#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${DOCKER_COMPOSE_DIR}/functions.bash"

log 'Running CrowdSec hub update and upgrade'
if container_is_running 'crowdsec'; then
  docker exec 'crowdsec' cscli hub update
  docker exec 'crowdsec' cscli hub upgrade
fi
log 'Ran CrowdSec hub update and upgrade'
