#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${DOCKER_COMPOSE_DIR}/functions.bash"

env_file="$(env_file)"
readonly env_file
if ! file_exists "${env_file}"; then
  cp "${env_file}.template" "${env_file}"
fi
function set_var() {
  set_env_file_var_if_not_defined "${env_file}" "$1" "${2:-}"
}
function get_var() {
  get_env_file_defined_var "${env_file}" "$1"
}

set_var 'RESTIC_PASSWORD' 'Restic encryption key --docker run --rm authelia/authelia:latest authelia crypto rand --length 64 --charset alphanumeric docker run --rm authelia/authelia:latest authelia crypto rand --length 64 --charset alphanumeric'
set_var 'B2_KEY_ID' 'Backblaze B2 application key ID'
set_var 'B2_KEY' 'Backblaze B2 application key'
set_var 'B2_BUCKET_ENDPOINT' 'Backblaze B2 endpoint'
set_var 'R2_KEY_ID' 'Cloudflare R2 application key ID'
set_var 'R2_KEY' 'Cloudflare R2 application key'
set_var 'R2_BUCKET_ENDPOINT' 'Cloudflare R2 endpoint'
set_var 'STORAGE_BOX_USERNAME' 'Hetzner Storage Box username'

create_dir "${BACKUP_DIR}/restic"

readonly ssh_key_dir="${DOCKER_APP_DATA_DIR}/restic/root/ssh"
create_dir "${ssh_key_dir}"
readonly ssh_key_file="${ssh_key_dir}/id_ed25519"
if ! file_exists "${ssh_key_file}"; then
  log "Generating SSH key"
  ssh-keygen -t 'ed25519' -C "${HOSTNAME} SSH key" -N '' -f "${ssh_key_file}"
  log "Generated SSH key"
  log "Uploading SSH key to Hetzner storage box"
  storage_box_username="$(get_var 'STORAGE_BOX_USERNAME')"
  readonly storage_box_username
  ssh -p '23' "${storage_box_username}@${storage_box_username}.your-storagebox.de" 'install-ssh-key' < "${ssh_key_file}.pub"
  log "Uploaded SSH key to Hetzner storage box"
  sudo chown -R 'root:' "${ssh_key_dir}"
fi

# $1 = repo desc
# $2 = service
function init_repo_if_not_exists() {
  local compose_file
  compose_file="$(this_script_dir)/compose.yaml"
  log "Checking if $1 repository exists"
  set +e
  docker compose --file "${compose_file}" run --rm "restic-$2" cat config > '/dev/null' 2>&1
  local exit_code="$?"
  set -e
  if [[ "${exit_code}" == '10' ]]; then
    log "$1 repository does not exist"
    if prompt_yn "Initialize $1 repository?"; then
      log "Initializing $1 repository"
      docker compose --file "${compose_file}" run --rm "restic-$2" init
      log "Initialized $1 repository"
    fi
  elif [[ "${exit_code}" != '0' ]]; then
    # run command again to print failure info
    docker compose --file "${compose_file}" run --rm "restic-$2" cat config
  else
    log "$1 repository exists"
  fi
}

init_repo_if_not_exists 'local' 'local'
init_repo_if_not_exists 'Backblaze B2' 'b2'
init_repo_if_not_exists 'Cloudflare R2' 'r2'
init_repo_if_not_exists 'Hetzner Storage Box' 'hetzner'
