#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${DOCKER_COMPOSE_DIR}/functions.bash"

# $1 = repo desc
# $2 = service
function run_backup() {
  log "Running $1 backup"
  docker compose --file "$(this_script_dir)/compose.yaml" run --rm "$2"
  log "Ran $1 backup"
}

run_backup 'B2' 'backup-app-data-b2'
run_backup 'Hetzner Storage Box' 'backup-app-data-hetzner'
run_backup 'local' 'backup-app-data-local'
