networks:
  proxy:
    external: true
  dozzle-socket-proxy:

services:

  dozzle-socket-proxy:
    image: ${SOCKET_PROXY_IMAGE:-lscr.io/linuxserver/socket-proxy}:${SOCKET_PROXY_IMAGE_TAG:-latest}
    container_name: dozzle-socket-proxy
    hostname: dozzle-socket-proxy
    read_only: true
    tmpfs:
      - /run
    restart: unless-stopped
    networks:
      - dozzle-socket-proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_SOCKET:?}:/var/run/docker.sock
    environment:
      ALLOW_START: 1
      ALLOW_STOP: 1
      ALLOW_RESTARTS: 1
      CONTAINERS: 1
      INFO: 1

  dozzle:
    image: ${DOZZLE_IMAGE:-amir20/dozzle}:${DOZZLE_IMAGE_TAG:-latest}
    container_name: dozzle
    hostname: dozzle
    restart: unless-stopped
    networks:
      - proxy
      - dozzle-socket-proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      DOZZLE_ENABLE_ACTIONS: true
      DOZZLE_HOSTNAME: dozzle.${DOMAIN_NAME:?}
      DOZZLE_LEVEL: ${DOZZLE_LEVEL:-info}
      DOZZLE_REMOTE_HOST: tcp://dozzle-socket-proxy:2375
    labels:
      - traefik.enable=true
      - traefik.http.routers.dozzle-rtr.entryPoints=websecure
      - traefik.http.routers.dozzle-rtr.rule=Host(`dozzle.${DOMAIN_NAME:?}`)
      - traefik.http.services.dozzle-svc.loadBalancer.server.port=8080
