include:
  - ../traefik-proxy-network.yaml

services:
  dozzle:
    extends:
      file: ../service-defaults.yaml
      service: service-defaults
    image: ${DOZZLE_IMAGE:-amir20/dozzle}:${DOZZLE_IMAGE_TAG:-latest}
    container_name: dozzle
    hostname: dozzle
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_SOCKET:?}:/var/run/docker.sock
    environment:
      DOZZLE_ENABLE_ACTIONS: true
    labels:
      - traefik.enable=true
      - traefik.http.routers.dozzle.entryPoints=websecure
      - traefik.http.routers.dozzle.rule=Host(`dozzle.${DOMAIN_NAME:?}`)
      - traefik.http.services.dozzle.loadBalancer.server.port=8080
