#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"

log_with_date 'Running daily tasks'

"$(this_script_dir)/run-crowdsec-hub-update-upgrade"

log_with_date 'Stopping stacks before backup'
stacks_to_restart=()
for stack in $(find "${DOCKER_APP_DATA_DIR}" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort); do
  if ! dir_exists "${DOCKER_COMPOSE_DIR}/${stack}"; then
    log_with_date "Stack does not exist: ${stack}"
    continue
  fi
  if [[ -z "$(docker compose --file "${DOCKER_COMPOSE_DIR}/${stack}/compose.yaml" ps --quiet)" ]]; then
    log_with_date "Stack is not running: ${stack}"
    continue
  fi
  log_with_date "Running docker compose down for: ${stack}"
  docker compose --file "${DOCKER_COMPOSE_DIR}/${stack}/compose.yaml" down
  stacks_to_restart+=("${stack}")
done
log_with_date 'Stopped stacks before backup'

log_with_date 'Running backups'
"$(this_script_dir)/run-backups" 'local' 'b2' 'r2'
log_with_date 'Ran backups'

# Run Watchtower here rather than after restarting stacks, so the containers in
# those stacks can be updated before starting them back up.
"$(this_script_dir)/run-watchtower"

log_with_date 'Starting stacks stopped for backup'
for stack in "${stacks_to_restart[@]}"; do
  log_with_date "Running docker compose up for: ${stack}"
  docker compose --file "${DOCKER_COMPOSE_DIR}/${stack}/compose.yaml" up --detach
done
log_with_date 'Started stacks stopped for backup'

log_with_date 'Running backup maintenance'
"$(this_script_dir)/run-backup-maintenance" 'local' 'b2' 'r2'
log_with_date 'Ran backup maintenance'

log_with_date "Ran daily tasks in $(shell_elapsed_time)"
