#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"

log_with_date 'Running daily tasks'

"$(this_script_dir)/run-crowdsec-hub-update-upgrade"

log_with_date 'Stopping stacks before backup'
compose_files_to_restart=()
for compose_file in $(docker compose ls | tail --lines '+2' | awk '{ print $3 }' | sort); do
  stack="$(basename "$(dirname "${compose_file}")")"
  app_data_dir="${DOCKER_APP_DATA_DIR}/${stack}"
  if ! dir_exists "${app_data_dir}"; then
    log_with_date "Stack does not have app data: ${stack}"
  else
    log "Running docker compose down for: ${stack}"
    docker compose --file "${compose_file}" down
    compose_files_to_restart+=("${compose_file}")
  fi
done
log_with_date 'Stopped stacks before backup'

log_with_date 'Running backups'
"$(this_script_dir)/run-backups" 'local' 'b2' 'r2'
log_with_date 'Ran backups'

# Run Watchtower here rather than after restarting stacks, so the containers in
# those stacks can be updated before starting them back up.
"$(this_script_dir)/run-watchtower"

log_with_date 'Starting stacks stopped for backup'
for compose_file in "${compose_files_to_restart[@]}"; do
  stack="$(basename "$(dirname "${compose_file}")")"
  log_with_date "Running docker compose up for: ${stack}"
  docker compose --file "${compose_file}" up --detach
done
log_with_date 'Started stacks stopped for backup'

log_with_date 'Running backup maintenance'
"$(this_script_dir)/run-backup-maintenance" 'local' 'b2' 'r2'
log_with_date 'Ran backup maintenance'

log_with_date "Ran daily tasks in $(shell_elapsed_time)"
