#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${DOCKER_DIR}/scripts/common.bash"

copy_env_file_template

prompt_set_env_file_val 'DISCORD_WEBHOOK_ID'
prompt_set_env_file_val 'DISCORD_TOKEN'
