#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${DOCKER_DIR}/scripts/common.bash"

docker compose \
  --file "${DOCKER_COMPOSE_DIR}/watchtower/compose.yaml" \
  run \
  --rm \
  --name 'watchtower' \
  'watchtower' \
  "$@"
