networks:
  proxy:
    external: true

services:
  beszel:
    image: ${BESZEL_IMAGE:-henrygd/beszel}:${BESZEL_IMAGE_TAG:-latest}
    container_name: beszel
    hostname: beszel
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - ./id_ed25519:/beszel_data/id_ed25519:ro
      - ./id_ed25519.pub:/beszel_data/id_ed25519.pub:ro
      - ${DOCKER_APP_DATA_DIR:?}/beszel/beszel_data:/beszel_data
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.beszel-rtr.rule=Host(`beszel.${DOMAIN_NAME:?}`)
      - traefik.http.services.beszel-svc.loadBalancer.server.port=8090
