#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${DOCKER_COMPOSE_DIR}/functions.bash"

env_file="$(env_file)"
readonly env_file
if ! file_exists "${env_file}"; then
  cp "${env_file}.template" "${env_file}"
fi
function set_var() {
  set_env_file_var_if_not_defined "${env_file}" "$1" "${2:-}"
}
function get_var() {
  get_env_file_defined_var "${env_file}" "$1"
}

readonly ssh_key_file="$(this_script_dir)/id_ed25519"
if ! file_exists "${ssh_key_file}"; then
  log "Generating SSH key"
  ssh-keygen -t 'ed25519' -C "beszel SSH key" -N '' -f "${ssh_key_file}"
  log "Generated SSH key"
fi