## TODO komodo?
networks:
  proxy:
    external: true
  dockge-socket-proxy:
    name: dockge-socket-proxy

services:

  dockge-socket-proxy:
    image: ${SOCKET_PROXY_IMAGE:-lscr.io/linuxserver/socket-proxy}:${SOCKET_PROXY_IMAGE_TAG:-latest}
    container_name: dockge-socket-proxy
    hostname: dockge-socket-proxy
    read_only: true
    tmpfs:
      - /run
    restart: unless-stopped
    networks:
      - dockge-socket-proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_SOCKET:?}:/var/run/docker.sock
    environment:
      CONTAINERS: 1
      EXEC: 1
      IMAGES: 1
      INFO: 1
      POST: 1
      SERVICES: 1

  dockge:
    image: ${DOCKGE_IMAGE:-louislam/dockge}:${DOCKGE_IMAGE_TAG:-latest}
    container_name: dockge
    hostname: dockge
    restart: unless-stopped
    networks:
      - proxy
      - dockge-socket-proxy
    depends_on:
      - dockge-socket-proxy
    volumes:
      - ${DOCKER_APP_DATA_DIR:?}/dockge:/app/data
      - ${DOCKER_COMPOSE_DIR:?}:/opt/stacks
      - /etc/localtime:/etc/localtime:ro
    environment:
      DOCKER_HOST: tcp://dockge-socket-proxy:2375
      DOCKGE_STACKS_DIR: /opt/stacks/ # TODO necessary?
      # The below env vars are to prevent issues when dockge evaluates a compose file.
      DOCKER_APP_DATA_DIR: ${DOCKER_APP_DATA_DIR:?}
      DOCKER_SOCKET: ${DOCKER_SOCKET:?}
      DOCKER_TZ: ${DOCKER_TZ:?}
      DOMAIN_NAME: ${DOMAIN_NAME:?}
      TAILNET_IP: ${TAILNET_IP:?}
    labels:
      - traefik.docker.network=proxy
      - traefik.enable=true
      - traefik.http.routers.dockge-rtr.entryPoints=websecure
      - traefik.http.routers.dockge-rtr.middlewares=default-chain-mdw
      - traefik.http.routers.dockge-rtr.rule=Host(`dockge.${DOMAIN_NAME:?}`)
      - traefik.http.services.dockge-svc.loadBalancer.server.port=5001
