services:
  dockge:
    image: louislam/dockge:latest
    container_name: dockge
    hostname: dockge
    restart: unless-stopped
    user: ${PUID:?}:${PGID:?}
    ports:
      - "${TAILNET_IP:?}:${DOCKGE_PORT:?}:5001"
    volumes:
      - ${DOCKER_COMPOSE_DIR:?}:/opt/stacks
      - ${DOCKER_APP_DATA_DIR:?}/dockge:/app/data
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_SOCKET:?}:/var/run/docker.sock
    environment:
      DOCKGE_STACKS_DIR: /opt/stacks/ # TODO necessary?
