## TODO komodo?
networks:
  proxy:
    external: true
  socket-proxy:

services:

  dockge-socket-proxy:
    image: ${SOCKET_PROXY_IMAGE:-lscr.io/linuxserver/socket-proxy}:${SOCKET_PROXY_IMAGE_TAG:-latest}
    container_name: dockge-socket-proxy
    hostname: dockge-socket-proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /run
    networks:
      - socket-proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_SOCKET:?}:/var/run/docker.sock
    environment:
      ALLOW_RESTARTS: 1
      ALLOW_START: 1
      ALLOW_STOP: 1
      CONTAINERS: 1
      EXEC: 1
      IMAGES: 1
      INFO: 1
      NETWORKS: 1
      POST: 1
      SERVICES: 1

  dockge:
    image: ${DOCKGE_IMAGE:-louislam/dockge}:${DOCKGE_IMAGE_TAG:-latest}
    container_name: dockge
    hostname: dockge
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - socket-proxy
    depends_on:
      - dockge-socket-proxy
    volumes:
      - ${DOCKER_COMPOSE_DIR:?}:/opt/stacks
      - ${DOCKER_APP_DATA_DIR:?}/dockge/app/data:/app/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      DOCKER_HOST: tcp://dockge-socket-proxy:2375
      # The below env vars are to prevent issues when dockge evaluates a compose file.
      BACKUP_DIR: ${BACKUP_DIR:?}
      DATA_DIR: ${DATA_DIR:?}
      DOCKER_APP_DATA_DIR: ${DOCKER_APP_DATA_DIR:?}
      DOCKER_COMPOSE_DIR: ${DOCKER_COMPOSE_DIR:?}
      DOCKER_DIR: ${DOCKER_DIR:?}
      DOCKER_LOGS_DIR: ${DOCKER_LOGS_DIR:?}
      DOCKER_PROXY_NETWORK_GATEWAY: ${DOCKER_PROXY_NETWORK_GATEWAY:?}
      DOCKER_PROXY_NETWORK_SUBNET_CIDR: ${DOCKER_PROXY_NETWORK_SUBNET_CIDR:?}
      DOCKER_SOCKET: ${DOCKER_SOCKET:?}
      DOCKER_TZ: ${DOCKER_TZ:?}
      DOMAIN_NAME: ${DOMAIN_NAME:?}
      DOMAIN_NAME_REGEX: ${DOMAIN_NAME_REGEX:?}
      PGID: ${PGID:?}
      PUID: ${PUID:?}
      TAILNET_IP: ${TAILNET_IP:?}
      USER: ${USER:?}
    labels:
      - traefik.http.routers.dockge-rtr.rule=Host(`dockge.${DOMAIN_NAME:?}`)
      - traefik.http.services.dockge-svc.loadBalancer.server.port=5001
